import pickle

path = "/home/kenpeter/work/theos/dataset_cache/synthetic_code_reasoning.pkl"
texts = pickle.load(open(path, "rb"))

new_samples = [
    # --- Arrays & Hashing ---
    (f"<|user|>\nGiven an integer array, move all zeros to the end while maintaining relative order of non-zero elements.\n<|assistant|>\ndef move_zeros(nums):\n    pos = 0\n    for i in range(len(nums)):\n        if nums[i] != 0:\n            nums[pos], nums[i] = nums[i], nums[pos]\n            pos += 1\n    return nums\n<|end|>"),
    (f"<|user|>\nFind the maximum product of two integers in an array.\n<|assistant|>\ndef max_product(nums):\n    nums.sort()\n    return max(nums[0]*nums[1], nums[-1]*nums[-2])\n<|end|>"),
    (f"<|user|>\nGiven an array, return True if any value appears at least twice.\n<|assistant|>\ndef contains_duplicate(nums):\n    return len(nums) != len(set(nums))\n<|end|>"),
    (f"<|user|>\nGiven two strings s and t, return True if t is an anagram of s.\n<|assistant|>\ndef is_anagram(s, t):\n    return sorted(s) == sorted(t)\n<|end|>"),
    (f"<|user|>\nFind the single element in an array where every other element appears twice.\n<|assistant|>\ndef single_number(nums):\n    res = 0\n    for n in nums:\n        res ^= n\n    return res\n<|end|>"),
    (f"<|user|>\nGiven an array of integers nums and an integer k, return the k most frequent elements.\n<|assistant|>\ndef top_k_frequent(nums, k):\n    freq = {}\n    for n in nums:\n        freq[n] = freq.get(n, 0) + 1\n    buckets = [[] for _ in range(len(nums) + 1)]\n    for n, f in freq.items():\n        buckets[f].append(n)\n    res = []\n    for i in range(len(buckets) - 1, 0, -1):\n        for n in buckets[i]:\n            res.append(n)\n            if len(res) == k:\n                return res\n    return res\n<|end|>"),
    (f"<|user|>\nGiven an array nums, return an array output where output[i] is product of all elements except nums[i] without using division.\n<|assistant|>\ndef product_except_self(nums):\n    n = len(nums)\n    res = [1] * n\n    left = 1\n    for i in range(n):\n        res[i] = left\n        left *= nums[i]\n    right = 1\n    for i in range(n - 1, -1, -1):\n        res[i] *= right\n        right *= nums[i]\n    return res\n<|end|>"),
    (f"<|user|>\nFind the longest consecutive sequence of integers in an unsorted array.\n<|assistant|>\ndef longest_consecutive(nums):\n    s = set(nums)\n    best = 0\n    for n in s:\n        if n - 1 not in s:\n            cur = n\n            streak = 1\n            while cur + 1 in s:\n                cur += 1\n                streak += 1\n            best = max(best, streak)\n    return best\n<|end|>"),
    (f"<|user|>\nGiven an array of meeting time intervals, determine if a person could attend all meetings.\n<|assistant|>\ndef can_attend(intervals):\n    intervals.sort(key=lambda x: x[0])\n    for i in range(1, len(intervals)):\n        if intervals[i][0] < intervals[i-1][1]:\n            return False\n    return True\n<|end|>"),
    (f"<|user|>\nGiven a non-empty array of integers, return the majority element (appears more than n/2 times).\n<|assistant|>\ndef majority_element(nums):\n    count = 0\n    cand = None\n    for n in nums:\n        if count == 0:\n            cand = n\n        count += 1 if n == cand else -1\n    return cand\n<|end|>"),
    # --- Two Pointers ---
    (f"<|user|>\nGiven a sorted array and a target, return indices of two numbers that sum to target.\n<|assistant|>\ndef two_sum_sorted(nums, target):\n    l, r = 0, len(nums) - 1\n    while l < r:\n        s = nums[l] + nums[r]\n        if s == target:\n            return [l, r]\n        elif s < target:\n            l += 1\n        else:\n            r -= 1\n    return []\n<|end|>"),
    (f"<|user|>\nGiven an integer array nums, return all triplets that sum to zero.\n<|assistant|>\ndef three_sum(nums):\n    nums.sort()\n    res = []\n    for i in range(len(nums) - 2):\n        if i > 0 and nums[i] == nums[i-1]:\n            continue\n        l, r = i + 1, len(nums) - 1\n        while l < r:\n            s = nums[i] + nums[l] + nums[r]\n            if s == 0:\n                res.append([nums[i], nums[l], nums[r]])\n                while l < r and nums[l] == nums[l+1]:\n                    l += 1\n                while l < r and nums[r] == nums[r-1]:\n                    r -= 1\n                l += 1\n                r -= 1\n            elif s < 0:\n                l += 1\n            else:\n                r -= 1\n    return res\n<|end|>"),
    (f"<|user|>\nGiven a string, find the length of the longest substring without repeating characters.\n<|assistant|>\ndef length_of_longest_substring(s):\n    chars = set()\n    l = 0\n    best = 0\n    for r in range(len(s)):\n        while s[r] in chars:\n            chars.remove(s[l])\n            l += 1\n        chars.add(s[r])\n        best = max(best, r - l + 1)\n    return best\n<|end|>"),
    (f"<|user|>\nGiven n non-negative integers representing height of walls, compute how much water it can trap.\n<|assistant|>\ndef trap(height):\n    l, r = 0, len(height) - 1\n    left_max = right_max = 0\n    water = 0\n    while l < r:\n        if height[l] < height[r]:\n            if height[l] >= left_max:\n                left_max = height[l]\n            else:\n                water += left_max - height[l]\n            l += 1\n        else:\n            if height[r] >= right_max:\n                right_max = height[r]\n            else:\n                water += right_max - height[r]\n            r -= 1\n    return water\n<|end|>"),
    (f"<|user|>\nGiven two sorted arrays, merge them into one sorted array in-place (first array has extra space).\n<|assistant|>\ndef merge_sorted(nums1, m, nums2, n):\n    i, j, k = m - 1, n - 1, m + n - 1\n    while j >= 0:\n        if i >= 0 and nums1[i] > nums2[j]:\n            nums1[k] = nums1[i]\n            i -= 1\n        else:\n            nums1[k] = nums2[j]\n            j -= 1\n        k -= 1\n    return nums1\n<|end|>"),
    (f"<|user|>\nGiven a string, find the longest palindromic substring.\n<|assistant|>\ndef longest_palindrome(s):\n    def expand(l, r):\n        while l >= 0 and r < len(s) and s[l] == s[r]:\n            l -= 1\n            r += 1\n        return s[l+1:r]\n    best = ''\n    for i in range(len(s)):\n        odd = expand(i, i)\n        even = expand(i, i + 1)\n        best = max(best, odd, even, key=len)\n    return best\n<|end|>"),
    # --- Sliding Window ---
    (f"<|user|>\nGiven an array of positive integers and a target sum, return minimal length of contiguous subarray with sum >= target.\n<|assistant|>\ndef min_subarray_len(target, nums):\n    l = total = 0\n    best = float('inf')\n    for r in range(len(nums)):\n        total += nums[r]\n        while total >= target:\n            best = min(best, r - l + 1)\n            total -= nums[l]\n            l += 1\n    return 0 if best == float('inf') else best\n<|end|>"),
    (f"<|user|>\nGiven a string s and a string p, return all start indices of p's anagrams in s.\n<|assistant|>\ndef find_anagrams(s, p):\n    need = {}\n    for c in p:\n        need[c] = need.get(c, 0) + 1\n    have = {}\n    need_len = len(need)\n    have_len = 0\n    l = 0\n    res = []\n    for r in range(len(s)):\n        c = s[r]\n        have[c] = have.get(c, 0) + 1\n        if c in need and have[c] == need[c]:\n            have_len += 1\n        if r - l + 1 > len(p):\n            left_c = s[l]\n            if left_c in need and have[left_c] == need[left_c]:\n                have_len -= 1\n            have[left_c] -= 1\n            l += 1\n        if have_len == need_len:\n            res.append(l)\n    return res\n<|end|>"),
    (f"<|user|>\nGiven a binary array, find max number of consecutive 1s if you can flip at most k zeros.\n<|assistant|>\ndef longest_ones(nums, k):\n    l = zero_count = 0\n    best = 0\n    for r in range(len(nums)):\n        if nums[r] == 0:\n            zero_count += 1\n        while zero_count > k:\n            if nums[l] == 0:\n                zero_count -= 1\n            l += 1\n        best = max(best, r - l + 1)\n    return best\n<|end|>"),
    # --- Stack ---
    (f"<|user|>\nGiven a string containing just the characters '(', ')', '{', '}', '[' and ']', determine if it is valid.\n<|assistant|>\ndef is_valid(s):\n    pairs = {')': '(', '}': '{', ']': '['}\n    stack = []\n    for c in s:\n        if c in pairs:\n            if not stack or stack[-1] != pairs[c]:\n                return False\n            stack.pop()\n        else:\n            stack.append(c)\n    return not stack\n<|end|>"),
    (f"<|user|>\nDesign a stack that supports push, pop, top, and retrieving the minimum element.\n<|assistant|>\ndef __init__(self):\n    self.stack = []\n    self.mins = []\n\ndef push(self, val):\n    self.stack.append(val)\n    if not self.mins or val <= self.mins[-1]:\n        self.mins.append(val)\n\ndef pop(self):\n    if self.stack:\n        val = self.stack.pop()\n        if val == self.mins[-1]:\n            self.mins.pop()\n        return val\n\ndef top(self):\n    return self.stack[-1] if self.stack else None\n\ndef get_min(self):\n    return self.mins[-1] if self.mins else None\n<|end|>"),
    (f"<|user|>\nGiven an array of integers, return an array where each element is the next greater element to the right, else -1.\n<|assistant|>\ndef next_greater(nums):\n    res = [-1] * len(nums)\n    stack = []\n    for i in range(len(nums)):\n        while stack and nums[stack[-1]] < nums[i]:\n            idx = stack.pop()\n            res[idx] = nums[i]\n        stack.append(i)\n    return res\n<|end|>"),
    (f"<|user|>\nEvaluate the value of an arithmetic expression in Reverse Polish Notation.\n<|assistant|>\ndef eval_rpn(tokens):\n    stack = []\n    ops = {'+': lambda a,b: a+b, '-': lambda a,b: a-b, '*': lambda a,b: a*b, '/': lambda a,b: int(a/b)}\n    for t in tokens:\n        if t in ops:\n            b = stack.pop()\n            a = stack.pop()\n            stack.append(ops[t](a, b))\n        else:\n            stack.append(int(t))\n    return stack[0]\n<|end|>"),
    (f"<|user|>\nGiven a string with digits from 2-9, return all possible letter combinations.\n<|assistant|>\ndef letter_combinations(digits):\n    if not digits:\n        return []\n    mapping = {'2':'abc','3':'def','4':'ghi','5':'jkl','6':'mno','7':'pqrs','8':'tuv','9':'wxyz'}\n    res = ['']\n    for d in digits:\n        res = [prefix + c for prefix in res for c in mapping[d]]\n    return res\n<|end|>"),
    # --- Binary Search ---
    (f"<|user|>\nGiven a sorted array and a target, return the index if found, else -1.\n<|assistant|>\ndef binary_search(nums, target):\n    l, r = 0, len(nums) - 1\n    while l <= r:\n        mid = (l + r) // 2\n        if nums[mid] == target:\n            return mid\n        elif nums[mid] < target:\n            l = mid + 1\n        else:\n            r = mid - 1\n    return -1\n<|end|>"),
    (f"<|user|>\nFind the square root of a non-negative integer x rounded down.\n<|assistant|>\ndef my_sqrt(x):\n    if x < 2:\n        return x\n    l, r = 1, x // 2\n    while l <= r:\n        mid = (l + r) // 2\n        if mid * mid == x:\n            return mid\n        elif mid * mid < x:\n            l = mid + 1\n        else:\n            r = mid - 1\n    return r\n<|end|>"),
    (f"<|user|>\nSuppose an array sorted in ascending order is rotated. Search for a target value.\n<|assistant|>\ndef search_rotated(nums, target):\n    l, r = 0, len(nums) - 1\n    while l <= r:\n        mid = (l + r) // 2\n        if nums[mid] == target:\n            return mid\n        if nums[l] <= nums[mid]:\n            if nums[l] <= target < nums[mid]:\n                r = mid - 1\n            else:\n                l = mid + 1\n        else:\n            if nums[mid] < target <= nums[r]:\n                l = mid + 1\n            else:\n                r = mid - 1\n    return -1\n<|end|>"),
    (f"<|user|>\nFind the minimum element in a rotated sorted array.\n<|assistant|>\ndef find_min_rotated(nums):\n    l, r = 0, len(nums) - 1\n    while l < r:\n        mid = (l + r) // 2\n        if nums[mid] > nums[r]:\n            l = mid + 1\n        else:\n            r = mid\n    return nums[l]\n<|end|>"),
    (f"<|user|>\nGiven a sorted array with duplicates, find the first and last position of a target.\n<|assistant|>\ndef search_range(nums, target):\n    def find_left():\n        l, r = 0, len(nums) - 1\n        while l <= r:\n            mid = (l + r) // 2\n            if nums[mid] < target:\n                l = mid + 1\n            else:\n                r = mid - 1\n        return l\n    def find_right():\n        l, r = 0, len(nums) - 1\n        while l <= r:\n            mid = (l + r) // 2\n            if nums[mid] <= target:\n                l = mid + 1\n            else:\n                r = mid - 1\n        return r\n    left = find_left()\n    right = find_right()\n    if left <= right < len(nums) and nums[left] == target == nums[right]:\n        return [left, right]\n    return [-1, -1]\n<|end|>"),
    # --- Linked Lists ---
    (f"<|user|>\nReverse a singly linked list.\n<|assistant|>\ndef reverse_list(head):\n    prev = None\n    cur = head\n    while cur:\n        nxt = cur.next\n        cur.next = prev\n        prev = cur\n        cur = nxt\n    return prev\n<|end|>"),
    (f"<|user|>\nGiven the head of a linked list, detect if there is a cycle.\n<|assistant|>\ndef has_cycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow == fast:\n            return True\n    return False\n<|end|>"),
    (f"<|user|>\nMerge two sorted linked lists into one sorted list.\n<|assistant|>\ndef merge_two_lists(l1, l2):\n    dummy = cur = ListNode(0)\n    while l1 and l2:\n        if l1.val < l2.val:\n            cur.next = l1\n            l1 = l1.next\n        else:\n            cur.next = l2\n            l2 = l2.next\n        cur = cur.next\n    cur.next = l1 or l2\n    return dummy.next\n<|end|>"),
    (f"<|user|>\nRemove the n-th node from the end of a linked list.\n<|assistant|>\ndef remove_nth_from_end(head, n):\n    dummy = ListNode(0, head)\n    fast = slow = dummy\n    for _ in range(n):\n        fast = fast.next\n    while fast.next:\n        fast = fast.next\n        slow = slow.next\n    slow.next = slow.next.next\n    return dummy.next\n<|end|>"),
    (f"<|user|>\nFind the middle node of a linked list.\n<|assistant|>\ndef middle_node(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n    return slow\n<|end|>"),
    (f"<|user|>\nGiven a linked list, return the node where a cycle begins, or None.\n<|assistant|>\ndef detect_cycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow == fast:\n            slow = head\n            while slow != fast:\n                slow = slow.next\n                fast = fast.next\n            return slow\n    return None\n<|end|>"),
    (f"<|user|>\nGiven the head of a linked list, reorder it as L0->Ln->L1->Ln-1->...\n<|assistant|>\ndef reorder_list(head):\n    if not head or not head.next:\n        return\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n    second = slow.next\n    slow.next = None\n    prev = None\n    cur = second\n    while cur:\n        nxt = cur.next\n        cur.next = prev\n        prev = cur\n        cur = nxt\n    first = head\n    second = prev\n    while second:\n        tmp1, tmp2 = first.next, second.next\n        first.next = second\n        second.next = tmp1\n        first = tmp1\n        second = tmp2\n<|end|>"),
    (f"<|user|>\nAdd two numbers represented as linked lists (digits in reverse order).\n<|assistant|>\ndef add_two_numbers(l1, l2):\n    dummy = cur = ListNode(0)\n    carry = 0\n    while l1 or l2 or carry:\n        v1 = l1.val if l1 else 0\n        v2 = l2.val if l2 else 0\n        total = v1 + v2 + carry\n        carry = total // 10\n        cur.next = ListNode(total % 10)\n        cur = cur.next\n        l1 = l1.next if l1 else None\n        l2 = l2.next if l2 else None\n    return dummy.next\n<|end|>"),
    (f"<|user|>\nCheck if a linked list is a palindrome.\n<|assistant|>\ndef is_palindrome(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n    prev = None\n    while slow:\n        nxt = slow.next\n        slow.next = prev\n        prev = slow\n        slow = nxt\n    left, right = head, prev\n    while right:\n        if left.val != right.val:\n            return False\n        left = left.next\n        right = right.next\n    return True\n<|end|>"),
    # --- Trees ---
    (f"<|user|>\nFind the maximum depth of a binary tree.\n<|assistant|>\ndef max_depth(root):\n    if not root:\n        return 0\n    return 1 + max(max_depth(root.left), max_depth(root.right))\n<|end|>"),
    (f"<|user|>\nCheck if a binary tree is symmetric around its center.\n<|assistant|>\ndef is_symmetric(root):\n    def check(l, r):\n        if not l and not r:\n            return True\n        if not l or not r or l.val != r.val:\n            return False\n        return check(l.left, r.right) and check(l.right, r.left)\n    return check(root.left, root.right) if root else True\n<|end|>"),
    (f"<|user|>\nGiven a binary tree, return its inorder traversal iteratively.\n<|assistant|>\ndef inorder_traversal(root):\n    res, stack = [], []\n    cur = root\n    while cur or stack:\n        while cur:\n            stack.append(cur)\n            cur = cur.left\n        cur = stack.pop()\n        res.append(cur.val)\n        cur = cur.right\n    return res\n<|end|>"),
    (f"<|user|>\nGiven two binary trees, check if they are the same.\n<|assistant|>\ndef is_same_tree(p, q):\n    if not p and not q:\n        return True\n    if not p or not q or p.val != q.val:\n        return False\n    return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)\n<|end|>"),
    (f"<|user|>\nGiven a binary tree, return level order traversal (left to right, level by level).\n<|assistant|>\ndef level_order(root):\n    if not root:\n        return []\n    res, q = [], [root]\n    while q:\n        level = []\n        for _ in range(len(q)):\n            node = q.pop(0)\n            level.append(node.val)\n            if node.left:\n                q.append(node.left)\n                if node.right:\n                    q.append(node.right)\n            elif node.right:\n                q.append(node.right)\n        res.append(level)\n    return res\n<|end|>"),
    (f"<|user|>\nGiven the root of a binary tree, check if it's a valid binary search tree.\n<|assistant|>\ndef is_valid_bst(root):\n    def valid(node, lo, hi):\n        if not node:\n            return True\n        if node.val <= lo or node.val >= hi:\n            return False\n        return valid(node.left, lo, node.val) and valid(node.right, node.val, hi)\n    return valid(root, float('-inf'), float('inf'))\n<|end|>"),
    (f"<|user|>\nConvert a sorted array to a height-balanced binary search tree.\n<|assistant|>\ndef sorted_array_to_bst(nums):\n    def build(l, r):\n        if l > r:\n            return None\n        mid = (l + r) // 2\n        node = TreeNode(nums[mid])\n        node.left = build(l, mid - 1)\n        node.right = build(mid + 1, r)\n        return node\n    return build(0, len(nums) - 1)\n<|end|>"),
    (f"<|user|>\nGiven the root of a binary tree, find the diameter (longest path between any two nodes).\n<|assistant|>\ndef diameter_of_binary_tree(root):\n    best = 0\n    def depth(node):\n        nonlocal best\n        if not node:\n            return 0\n        l = depth(node.left)\n        r = depth(node.right)\n        best = max(best, l + r)\n        return 1 + max(l, r)\n    depth(root)\n    return best\n<|end|>"),
    (f"<|user|>\nGiven a binary tree, find the lowest common ancestor of two nodes.\n<|assistant|>\ndef lowest_common_ancestor(root, p, q):\n    if not root or root == p or root == q:\n        return root\n    left = lowest_common_ancestor(root.left, p, q)\n    right = lowest_common_ancestor(root.right, p, q)\n    if left and right:\n        return root\n    return left or right\n<|end|>"),
    (f"<|user|>\nSerialize and deserialize a binary tree.\n<|assistant|>\ndef serialize(root):\n    def dfs(node):\n        if not node:\n            return ['null']\n        return [str(node.val)] + dfs(node.left) + dfs(node.right)\n    return ','.join(dfs(root))\n\ndef deserialize(data):\n    vals = iter(data.split(','))\n    def dfs():\n        v = next(vals)\n        if v == 'null':\n            return None\n        node = TreeNode(int(v))\n        node.left = dfs()\n        node.right = dfs()\n        return node\n    return dfs()\n<|end|>"),
    # --- Tries ---
    (f"<|user|>\nImplement a Trie with insert, search, and startsWith methods.\n<|assistant|>\nclass Trie:\n    def __init__(self):\n        self.root = {}\n    def insert(self, word):\n        node = self.root\n        for c in word:\n            if c not in node:\n                node[c] = {}\n            node = node[c]\n        node['#'] = True\n    def search(self, word):\n        node = self.root\n        for c in word:\n            if c not in node:\n                return False\n            node = node[c]\n        return '#' in node\n    def startsWith(self, prefix):\n        node = self.root\n        for c in prefix:\n            if c not in node:\n                return False\n            node = node[c]\n        return True\n<|end|>"),
    (f"<|user|>\nGiven a list of words, find all words in a 2D board (word search II).\n<|assistant|>\ndef find_words(board, words):\n    trie = {}\n    for w in words:\n        node = trie\n        for c in w:\n            if c not in node:\n                node[c] = {}\n            node = node[c]\n        node['#'] = True\n    R, C = len(board), len(board[0])\n    res = set()\n    def dfs(r, c, node, prefix):\n        if '#' in node:\n            res.add(prefix)\n        if r < 0 or r >= R or c < 0 or c >= C or board[r][c] not in node:\n            return\n        tmp, board[r][c] = board[r][c], '#'\n        for dr, dc in [(1,0),(-1,0),(0,1),(0,-1)]:\n            dfs(r+dr, c+dc, node[tmp], prefix+tmp)\n        board[r][c] = tmp\n    for r in range(R):\n        for c in range(C):\n            if board[r][c] in trie:\n                dfs(r, c, trie, '')\n    return list(res)\n<|end|>"),
    # --- Heap / Priority Queue ---
    (f"<|user|>\nFind the k-th largest element in an unsorted array.\n<|assistant|>\ndef find_kth_largest(nums, k):\n    import heapq\n    heap = nums[:k]\n    heapq.heapify(heap)\n    for n in nums[k:]:\n        if n > heap[0]:\n            heapq.heapreplace(heap, n)\n    return heap[0]\n<|end|>"),
    (f"<|user|>\nMerge k sorted linked lists.\n<|assistant|>\ndef merge_k_lists(lists):\n    import heapq\n    dummy = cur = ListNode(0)\n    heap = []\n    for i, node in enumerate(lists):\n        if node:\n            heapq.heappush(heap, (node.val, i, node))\n    while heap:\n        val, i, node = heapq.heappop(heap)\n        cur.next = ListNode(val)\n        cur = cur.next\n        if node.next:\n            heapq.heappush(heap, (node.next.val, i, node.next))\n    return dummy.next\n<|end|>"),
    (f"<|user|>\nGiven an array of points, find the k closest to the origin.\n<|assistant|>\ndef k_closest(points, k):\n    import heapq\n    heap = []\n    for x, y in points:\n        dist = x*x + y*y\n        heapq.heappush(heap, (-dist, x, y))\n        if len(heap) > k:\n            heapq.heappop(heap)\n    return [[x, y] for _, x, y in heap]\n<|end|>"),
    (f"<|user|>\nFind the median from a data stream.\n<|assistant|>\nclass MedianFinder:\n    def __init__(self):\n        import heapq\n        self.small = []\n        self.large = []\n    def addNum(self, num):\n        import heapq\n        heapq.heappush(self.small, -num)\n        if self.small and self.large and -self.small[0] > self.large[0]:\n            val = -heapq.heappop(self.small)\n            heapq.heappush(self.large, val)\n        if len(self.small) > len(self.large) + 1:\n            val = -heapq.heappop(self.small)\n            heapq.heappush(self.large, val)\n        if len(self.large) > len(self.small) + 1:\n            val = heapq.heappop(self.large)\n            heapq.heappush(self.small, -val)\n    def findMedian(self):\n        if len(self.small) > len(self.large):\n            return -self.small[0]\n        elif len(self.large) > len(self.small):\n            return self.large[0]\n        return (-self.small[0] + self.large[0]) / 2\n<|end|>"),
    # --- Backtracking ---
    (f"<|user|>\nGiven n pairs of parentheses, generate all well-formed combinations.\n<|assistant|>\ndef generate_parenthesis(n):\n    res = []\n    def backtrack(s, l, r):\n        if len(s) == 2 * n:\n            res.append(s)\n            return\n        if l < n:\n            backtrack(s + '(', l + 1, r)\n        if r < l:\n            backtrack(s + ')', l, r + 1)\n    backtrack('', 0, 0)\n    return res\n<|end|>"),
    (f"<|user|>\nGiven a set of distinct integers, return all possible subsets.\n<|assistant|>\ndef subsets(nums):\n    res = [[]]\n    for n in nums:\n        res += [r + [n] for r in res]\n    return res\n<|end|>"),
    (f"<|user|>\nGiven an array of distinct integers, return all permutations.\n<|assistant|>\ndef permute(nums):\n    if len(nums) <= 1:\n        return [nums]\n    res = []\n    for i, n in enumerate(nums):\n        for p in permute(nums[:i] + nums[i+1:]):\n            res.append([n] + p)\n    return res\n<|end|>"),
    (f"<|user|>\nGiven a collection of numbers that may contain duplicates, return all unique permutations.\n<|assistant|>\ndef permute_unique(nums):\n    nums.sort()\n    res = []\n    used = [False] * len(nums)\n    def backtrack(path):\n        if len(path) == len(nums):\n            res.append(path[:])\n            return\n        for i in range(len(nums)):\n            if used[i] or (i > 0 and nums[i] == nums[i-1] and not used[i-1]):\n                continue\n            used[i] = True\n            path.append(nums[i])\n            backtrack(path)\n            path.pop()\n            used[i] = False\n    backtrack([])\n    return res\n<|end|>"),
    (f"<|user|>\nGiven a target and an array of distinct integers, return all unique combinations that sum to target (unlimited use of each).\n<|assistant|>\ndef combination_sum(candidates, target):\n    res = []\n    def dfs(start, path, total):\n        if total == target:\n            res.append(path[:])\n            return\n        if total > target:\n            return\n        for i in range(start, len(candidates)):\n            path.append(candidates[i])\n            dfs(i, path, total + candidates[i])\n            path.pop()\n    dfs(0, [], 0)\n    return res\n<|end|>"),
    (f"<|user|>\nSolve the N-Queens problem: place n queens on an nxn board so none attack each other.\n<|assistant|>\ndef solve_n_queens(n):\n    cols = set()\n    diag1 = set()\n    diag2 = set()\n    board = [['.'] * n for _ in range(n)]\n    res = []\n    def backtrack(r):\n        if r == n:\n            res.append([''.join(row) for row in board])\n            return\n        for c in range(n):\n            if c in cols or (r - c) in diag1 or (r + c) in diag2:\n                continue\n            board[r][c] = 'Q'\n            cols.add(c)\n            diag1.add(r - c)\n            diag2.add(r + c)\n            backtrack(r + 1)\n            board[r][c] = '.'\n            cols.remove(c)\n            diag1.remove(r - c)\n            diag2.remove(r + c)\n    backtrack(0)\n    return res\n<|end|>"),
    (f"<|user|>\nGiven a 2D grid of '1's (land) and '0's (water), count the number of islands.\n<|assistant|>\ndef num_islands(grid):\n    if not grid:\n        return 0\n    R, C = len(grid), len(grid[0])\n    def dfs(r, c):\n        if r < 0 or r >= R or c < 0 or c >= C or grid[r][c] == '0':\n            return\n        grid[r][c] = '0'\n        dfs(r+1, c)\n        dfs(r-1, c)\n        dfs(r, c+1)\n        dfs(r, c-1)\n    count = 0\n    for r in range(R):\n        for c in range(C):\n            if grid[r][c] == '1':\n                count += 1\n                dfs(r, c)\n    return count\n<|end|>"),
    # --- Graphs ---
    (f"<|user|>\nClone an undirected graph. Each node has a val and a list of neighbors.\n<|assistant|>\ndef clone_graph(node):\n    if not node:\n        return None\n    clones = {}\n    def dfs(n):\n        if n in clones:\n            return clones[n]\n        clone = Node(n.val)\n        clones[n] = clone\n        for nei in n.neighbors:\n            clone.neighbors.append(dfs(nei))\n        return clone\n    return dfs(node)\n<|end|>"),
    (f"<|user|>\nGiven a directed graph, return all nodes in topologically sorted order.\n<|assistant|>\ndef topological_sort(graph, n):\n    indegree = [0] * n\n    for u in graph:\n        for v in graph[u]:\n            indegree[v] += 1\n    q = [i for i in range(n) if indegree[i] == 0]\n    res = []\n    while q:\n        u = q.pop(0)\n        res.append(u)\n        for v in graph[u]:\n            indegree[v] -= 1\n            if indegree[v] == 0:\n                q.append(v)\n    return res if len(res) == n else []\n<|end|>"),
    (f"<|user|>\nGiven numCourses and prerequisites, return the order to take all courses.\n<|assistant|>\ndef find_order(num_courses, prerequisites):\n    graph = [[] for _ in range(num_courses)]\n    indegree = [0] * num_courses\n    for a, b in prerequisites:\n        graph[b].append(a)\n        indegree[a] += 1\n    q = [i for i in range(num_courses) if indegree[i] == 0]\n    res = []\n    while q:\n        u = q.pop(0)\n        res.append(u)\n        for v in graph[u]:\n            indegree[v] -= 1\n            if indegree[v] == 0:\n                q.append(v)\n    return res if len(res) == num_courses else []\n<|end|>"),
    (f"<|user|>\nGiven a 2D grid, find the number of distinct islands (identical shapes count once).\n<|assistant|>\ndef num_distinct_islands(grid):\n    if not grid:\n        return 0\n    R, C = len(grid), len(grid[0])\n    shapes = set()\n    def dfs(r, c, base_r, base_c, path):\n        if r < 0 or r >= R or c < 0 or c >= C or grid[r][c] == 0:\n            return\n        grid[r][c] = 0\n        path.append((r - base_r, c - base_c))\n        for dr, dc in [(1,0),(-1,0),(0,1),(0,-1)]:\n            dfs(r+dr, c+dc, base_r, base_c, path)\n    for r in range(R):\n        for c in range(C):\n            if grid[r][c] == 1:\n                path = []\n                dfs(r, c, r, c, path)\n                shapes.add(tuple(path))\n    return len(shapes)\n<|end|>"),
    (f"<|user|>\nGiven a 2D grid, find the shortest path from top-left to bottom-right (1=wall, 0=open). BFS.\n<|assistant|>\ndef shortest_path(grid):\n    if not grid or grid[0][0] == 1:\n        return -1\n    R, C = len(grid), len(grid[0])\n    q = [(0, 0, 1)]\n    visited = {(0, 0)}\n    while q:\n        r, c, d = q.pop(0)\n        if r == R-1 and c == C-1:\n            return d\n        for dr, dc in [(1,0),(-1,0),(0,1),(0,-1)]:\n            nr, nc = r+dr, c+dc\n            if 0 <= nr < R and 0 <= nc < C and grid[nr][nc] == 0 and (nr, nc) not in visited:\n                visited.add((nr, nc))\n                q.append((nr, nc, d+1))\n    return -1\n<|end|>"),
    (f"<|user|>\nGiven a 2D board containing 'X' and 'O', capture all 'O's surrounded by 'X'.\n<|assistant|>\ndef solve(board):\n    if not board:\n        return\n    R, C = len(board), len(board[0])\n    def dfs(r, c):\n        if r < 0 or r >= R or c < 0 or c >= C or board[r][c] != 'O':\n            return\n        board[r][c] = '#'\n        dfs(r+1, c)\n        dfs(r-1, c)\n        dfs(r, c+1)\n        dfs(r, c-1)\n    for i in range(R):\n        dfs(i, 0)\n        dfs(i, C-1)\n    for j in range(C):\n        dfs(0, j)\n        dfs(R-1, j)\n    for r in range(R):\n        for c in range(C):\n            if board[r][c] == 'O':\n                board[r][c] = 'X'\n            elif board[r][c] == '#':\n                board[r][c] = 'O'\n<|end|>"),
    # --- Dynamic Programming ---
    (f"<|user|>\nYou are climbing stairs. It takes n steps to reach the top. Each time you can climb 1 or 2 steps. Return number of distinct ways.\n<|assistant|>\ndef climb_stairs(n):\n    if n <= 2:\n        return n\n    a, b = 1, 2\n    for _ in range(3, n + 1):\n        a, b = b, a + b\n    return b\n<|end|>"),
    (f"<|user|>\nGiven an array of non-negative integers, return the maximum sum of non-adjacent elements.\n<|assistant|>\ndef house_robber(nums):\n    prev2 = prev1 = 0\n    for n in nums:\n        prev2, prev1 = prev1, max(prev1, prev2 + n)\n    return prev1\n<|end|>"),
    (f"<|user|>\nGiven a m x n grid, find the number of unique paths from top-left to bottom-right (only down or right).\n<|assistant|>\ndef unique_paths(m, n):\n    dp = [1] * n\n    for _ in range(1, m):\n        for j in range(1, n):\n            dp[j] += dp[j-1]\n    return dp[-1]\n<|end|>"),
    (f"<|user|>\nGiven a m x n grid with obstacles (1=obstacle), find number of unique paths.\n<|assistant|>\ndef unique_paths_with_obstacles(grid):\n    if grid[0][0] == 1:\n        return 0\n    m, n = len(grid), len(grid[0])\n    dp = [0] * n\n    dp[0] = 1\n    for r in range(m):\n        for c in range(n):\n            if grid[r][c] == 1:\n                dp[c] = 0\n            elif c > 0:\n                dp[c] += dp[c-1]\n    return dp[-1]\n<|end|>"),
    (f"<|user|>\nGiven a string and a dictionary of words, return True if the string can be segmented into dictionary words.\n<|assistant|>\ndef word_break(s, word_dict):\n    words = set(word_dict)\n    dp = [False] * (len(s) + 1)\n    dp[0] = True\n    for i in range(1, len(s) + 1):\n        for j in range(i):\n            if dp[j] and s[j:i] in words:\n                dp[i] = True\n                break\n    return dp[-1]\n<|end|>"),
    (f"<|user|>\nGiven a string and a dictionary, return all possible sentences formed by spaces.\n<|assistant|>\ndef word_break_ii(s, word_dict):\n    words = set(word_dict)\n    memo = {}\n    def dfs(start):\n        if start in memo:\n            return memo[start]\n        res = []\n        if start == len(s):\n            res.append('')\n            return res\n        for end in range(start + 1, len(s) + 1):\n            if s[start:end] in words:\n                for sub in dfs(end):\n                    res.append(s[start:end] + (' ' + sub if sub else ''))\n        memo[start] = res\n        return res\n    return dfs(0)\n<|end|>"),
    (f"<|user|>\nGiven an array of integers, find the contiguous subarray with the largest sum.\n<|assistant|>\ndef max_subarray(nums):\n    best = cur = nums[0]\n    for n in nums[1:]:\n        cur = max(n, cur + n)\n        best = max(best, cur)\n    return best\n<|end|>"),
    (f"<|user|>\nGiven two strings, return the length of their longest common subsequence.\n<|assistant|>\ndef longest_common_subsequence(a, b):\n    m, n = len(a), len(b)\n    dp = [[0] * (n + 1) for _ in range(m + 1)]\n    for i in range(1, m + 1):\n        for j in range(1, n + 1):\n            if a[i-1] == b[j-1]:\n                dp[i][j] = 1 + dp[i-1][j-1]\n            else:\n                dp[i][j] = max(dp[i-1][j], dp[i][j-1])\n    return dp[m][n]\n<|end|>"),
    (f"<|user|>\nGiven two strings, return the minimum edit distance (insert, delete, replace) to convert one to the other.\n<|assistant|>\ndef edit_distance(a, b):\n    m, n = len(a), len(b)\n    dp = [[0] * (n + 1) for _ in range(m + 1)]\n    for i in range(m + 1):\n        dp[i][0] = i\n    for j in range(n + 1):\n        dp[0][j] = j\n    for i in range(1, m + 1):\n        for j in range(1, n + 1):\n            if a[i-1] == b[j-1]:\n                dp[i][j] = dp[i-1][j-1]\n            else:\n                dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])\n    return dp[m][n]\n<|end|>"),
    (f"<|user|>\nGiven an array of non-negative integers representing the cost to step on each stair, find max you can avoid, actually find the minimum cost to reach the top.\n<|assistant|>\ndef min_cost_climbing(cost):\n    a, b = cost[0], cost[1]\n    for i in range(2, len(cost)):\n        a, b = b, cost[i] + min(a, b)\n    return min(a, b)\n<|end|>"),
    (f"<|user|>\nGiven a rod of length n and an array of prices, find max value by cutting.\n<|assistant|>\ndef rod_cutting(prices, n):\n    dp = [0] * (n + 1)\n    for i in range(1, n + 1):\n        for j in range(1, i + 1):\n            dp[i] = max(dp[i], prices[j-1] + dp[i - j])\n    return dp[n]\n<|end|>"),
    (f"<|user|>\nGiven a list of coin denominations and a total amount, find the fewest number of coins needed.\n<|assistant|>\ndef coin_change(coins, amount):\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for coin in coins:\n        for a in range(coin, amount + 1):\n            dp[a] = min(dp[a], 1 + dp[a - coin])\n    return -1 if dp[amount] == float('inf') else dp[amount]\n<|end|>"),
    (f"<|user|>\nGiven a list of coin denominations and a total amount, return number of combinations that sum to amount.\n<|assistant|>\ndef change(amount, coins):\n    dp = [0] * (amount + 1)\n    dp[0] = 1\n    for coin in coins:\n        for a in range(coin, amount + 1):\n            dp[a] += dp[a - coin]\n    return dp[amount]\n<|end|>"),
    (f"<|user|>\nGiven a triangle array, return the minimum path sum from top to bottom.\n<|assistant|>\ndef minimum_total(triangle):\n    dp = triangle[-1][:]\n    for i in range(len(triangle) - 2, -1, -1):\n        for j in range(len(triangle[i])):\n            dp[j] = triangle[i][j] + min(dp[j], dp[j+1])\n    return dp[0]\n<|end|>"),
    (f"<|user|>\nGiven an integer n, return the number of structurally unique BSTs that store values 1..n.\n<|assistant|>\ndef num_trees(n):\n    dp = [0] * (n + 1)\n    dp[0] = dp[1] = 1\n    for i in range(2, n + 1):\n        for j in range(1, i + 1):\n            dp[i] += dp[j-1] * dp[i-j]\n    return dp[n]\n<|end|>"),
    (f"<|user|>\nGiven a string s and a pattern p with '.' and '*' wildcards, implement regex matching.\n<|assistant|>\ndef is_match(s, p):\n    m, n = len(s), len(p)\n    dp = [[False] * (n + 1) for _ in range(m + 1)]\n    dp[0][0] = True\n    for j in range(2, n + 1):\n        if p[j-1] == '*':\n            dp[0][j] = dp[0][j-2]\n    for i in range(1, m + 1):\n        for j in range(1, n + 1):\n            if p[j-1] == s[i-1] or p[j-1] == '.':\n                dp[i][j] = dp[i-1][j-1]\n            elif p[j-1] == '*':\n                dp[i][j] = dp[i][j-2]\n                if p[j-2] == s[i-1] or p[j-2] == '.':\n                    dp[i][j] = dp[i][j] or dp[i-1][j]\n    return dp[m][n]\n<|end|>"),
    (f"<|user|>\nGiven a string, return the minimum number of cuts needed for every substring to be a palindrome.\n<|assistant|>\ndef min_cut(s):\n    n = len(s)\n    pal = [[False] * n for _ in range(n)]\n    for i in range(n):\n        pal[i][i] = True\n    for length in range(2, n + 1):\n        for i in range(n - length + 1):\n            j = i + length - 1\n            if s[i] == s[j] and (length <= 2 or pal[i+1][j-1]):\n                pal[i][j] = True\n    dp = [float('inf')] * n\n    for i in range(n):\n        if pal[0][i]:\n            dp[i] = 0\n        else:\n            for j in range(i):\n                if pal[j+1][i]:\n                    dp[i] = min(dp[i], dp[j] + 1)\n    return dp[-1]\n<|end|>"),
    (f"<|user|>\nGiven an array of integers, find the length of the longest increasing subsequence.\n<|assistant|>\ndef length_of_lis(nums):\n    tails = []\n    for n in nums:\n        l, r = 0, len(tails)\n        while l < r:\n            mid = (l + r) // 2\n            if tails[mid] < n:\n                l = mid + 1\n            else:\n                r = mid\n        if l == len(tails):\n            tails.append(n)\n        else:\n            tails[l] = n\n    return len(tails)\n<|end|>"),
    (f"<|user|>\nGiven an array of stock prices, find the maximum profit from one buy-sell transaction.\n<|assistant|>\ndef max_profit_one(prices):\n    min_price = float('inf')\n    profit = 0\n    for p in prices:\n        if p < min_price:\n            min_price = p\n        elif p - min_price > profit:\n            profit = p - min_price\n    return profit\n<|end|>"),
    (f"<|user|>\nGiven an array of stock prices, find the maximum profit from unlimited transactions.\n<|assistant|>\ndef max_profit_unlimited(prices):\n    profit = 0\n    for i in range(1, len(prices)):\n        if prices[i] > prices[i-1]:\n            profit += prices[i] - prices[i-1]\n    return profit\n<|end|>"),
    (f"<|user|>\nGiven an array of stock prices, find the maximum profit with at most two transactions.\n<|assistant|>\ndef max_profit_two(prices):\n    buy1 = buy2 = float('inf')\n    sell1 = sell2 = 0\n    for p in prices:\n        buy1 = min(buy1, p)\n        sell1 = max(sell1, p - buy1)\n        buy2 = min(buy2, p - sell1)\n        sell2 = max(sell2, p - buy2)\n    return sell2\n<|end|>"),
    # --- Greedy ---
    (f"<|user|>\nGiven an array of intervals, merge all overlapping intervals.\n<|assistant|>\ndef merge_intervals(intervals):\n    intervals.sort(key=lambda x: x[0])\n    res = [intervals[0]]\n    for s, e in intervals[1:]:\n        if s <= res[-1][1]:\n            res[-1][1] = max(res[-1][1], e)\n        else:\n            res.append([s, e])\n    return res\n<|end|>"),
    (f"<|user|>\nGiven an array of intervals, return the minimum number of intervals to remove to make the rest non-overlapping.\n<|assistant|>\ndef erase_overlap_intervals(intervals):\n    intervals.sort(key=lambda x: x[1])\n    end = float('-inf')\n    removed = 0\n    for s, e in intervals:\n        if s < end:\n            removed += 1\n        else:\n            end = e\n    return removed\n<|end|>"),
    (f"<|user|>\nGiven an array of non-negative integers, where each element is max jump length from that position, determine if you can reach the last index.\n<|assistant|>\ndef can_jump(nums):\n    reachable = 0\n    for i, n in enumerate(nums):\n        if i > reachable:\n            return False\n        reachable = max(reachable, i + n)\n    return True\n<|end|>"),
    (f"<|user|>\nGiven an array of non-negative integers, return the minimum number of jumps to reach the last index.\n<|assistant|>\ndef jump(nums):\n    jumps = cur_end = cur_farthest = 0\n    for i in range(len(nums) - 1):\n        cur_farthest = max(cur_farthest, i + nums[i])\n        if i == cur_end:\n            jumps += 1\n            cur_end = cur_farthest\n    return jumps\n<|end|>"),
    (f"<|user|>\nGiven a string s, remove duplicate letters so that every letter appears once in the smallest lexicographical result.\n<|assistant|>\ndef remove_duplicate_letters(s):\n    last_idx = {c: i for i, c in enumerate(s)}\n    seen = set()\n    stack = []\n    for i, c in enumerate(s):\n        if c in seen:\n            continue\n        while stack and c < stack[-1] and i < last_idx[stack[-1]]:\n            seen.remove(stack.pop())\n        stack.append(c)\n        seen.add(c)\n    return ''.join(stack)\n<|end|>"),
    # --- Bit Manipulation ---
    (f"<|user|>\nCount the number of 1 bits in an integer.\n<|assistant|>\ndef hamming_weight(n):\n    count = 0\n    while n:\n        count += n & 1\n        n >>= 1\n    return count\n<|end|>"),
    (f"<|user|>\nReverse bits of a given 32-bit unsigned integer.\n<|assistant|>\ndef reverse_bits(n):\n    res = 0\n    for _ in range(32):\n        res = (res << 1) | (n & 1)\n        n >>= 1\n    return res\n<|end|>"),
    (f"<|user|>\nGiven an integer n, return True if it's a power of two.\n<|assistant|>\ndef is_power_of_two(n):\n    return n > 0 and (n & (n - 1)) == 0\n<|end|>"),
    (f"<|user|>\nSum two integers without using + or -.\n<|assistant|>\ndef get_sum(a, b):\n    while b:\n        a, b = a ^ b, (a & b) << 1\n    return a\n<|end|>"),
    (f"<|user|>\nGiven an array where every element appears three times except one, find that single one.\n<|assistant|>\ndef single_number_ii(nums):\n    ones = twos = 0\n    for n in nums:\n        ones = (ones ^ n) & ~twos\n        twos = (twos ^ n) & ~ones\n    return ones\n<|end|>"),
    (f"<|user|>\nGiven two integers, determine if they are opposite signs without using comparison operators.\n<|assistant|>\ndef opposite_signs(a, b):\n    return (a ^ b) < 0\n<|end|>"),
    (f"<|user|>\nGiven an integer, find the position of the rightmost set bit (1-indexed).\n<|assistant|>\ndef rightmost_set_bit(n):\n    return (n & -n).bit_length()\n<|end|>"),
    # --- Math ---
    (f"<|user|>\nDetermine if an integer is a palindrome without converting to string.\n<|assistant|>\ndef is_palindrome_number(x):\n    if x < 0 or (x % 10 == 0 and x != 0):\n        return False\n    rev = 0\n    while x > rev:\n        rev = rev * 10 + x % 10\n        x //= 10\n    return x == rev or x == rev // 10\n<|end|>"),
    (f"<|user|>\nReturn the string representation of the integer n in base 7.\n<|assistant|>\ndef convert_to_base7(n):\n    if n == 0:\n        return '0'\n    sign = '' if n >= 0 else '-'\n    n = abs(n)\n    res = ''\n    while n:\n        res = str(n % 7) + res\n        n //= 7\n    return sign + res\n<|end|>"),
    (f"<|user|>\nGiven an integer n, return the n-th Fibonacci number.\n<|assistant|>\ndef fib(n):\n    if n <= 1:\n        return n\n    a, b = 0, 1\n    for _ in range(2, n + 1):\n        a, b = b, a + b\n    return b\n<|end|>"),
    (f"<|user|>\nGiven a string containing only digits, return the number of ways to decode it (A=1, ..., Z=26).\n<|assistant|>\ndef num_decodings(s):\n    if not s or s[0] == '0':\n        return 0\n    dp = [0] * (len(s) + 1)\n    dp[0] = 1\n    dp[1] = 1\n    for i in range(2, len(s) + 1):\n        one = int(s[i-1:i])\n        two = int(s[i-2:i])\n        if 1 <= one <= 9:\n            dp[i] += dp[i-1]\n        if 10 <= two <= 26:\n            dp[i] += dp[i-2]\n    return dp[-1]\n<|end|>"),
    (f"<|user|>\nCheck if an integer is a perfect square without using sqrt.\n<|assistant|>\ndef is_perfect_square(num):\n    l, r = 1, num\n    while l <= r:\n        mid = (l + r) // 2\n        sq = mid * mid\n        if sq == num:\n            return True\n        elif sq < num:\n            l = mid + 1\n        else:\n            r = mid - 1\n    return False\n<|end|>"),
    (f"<|user|>\nGiven an integer n, return the count of prime numbers less than n.\n<|assistant|>\ndef count_primes(n):\n    if n < 3:\n        return 0\n    sieve = [True] * n\n    sieve[0] = sieve[1] = False\n    for i in range(2, int(n ** 0.5) + 1):\n        if sieve[i]:\n            sieve[i*i:n:i] = [False] * ((n - i*i - 1) // i + 1)\n    return sum(sieve)\n<|end|>"),
    (f"<|user|>\nGiven two strings representing non-negative integers, return their product as a string.\n<|assistant|>\ndef multiply_strings(num1, num2):\n    if num1 == '0' or num2 == '0':\n        return '0'\n    res = [0] * (len(num1) + len(num2))\n    for i in range(len(num1) - 1, -1, -1):\n        for j in range(len(num2) - 1, -1, -1):\n            prod = int(num1[i]) * int(num2[j])\n            p1, p2 = i + j, i + j + 1\n            total = prod + res[p2]\n            res[p1] += total // 10\n            res[p2] = total % 10\n    start = 0\n    while start < len(res) and res[start] == 0:\n        start += 1\n    return ''.join(map(str, res[start:]))\n<|end|>"),
    (f"<|user|>\nGiven an integer x, return x reversed (with sign handling, return 0 if overflow).\n<|assistant|>\ndef reverse_integer(x):\n    sign = 1 if x >= 0 else -1\n    x = abs(x)\n    rev = 0\n    while x:\n        rev = rev * 10 + x % 10\n        x //= 10\n    rev *= sign\n    if rev < -2**31 or rev > 2**31 - 1:\n        return 0\n    return rev\n<|end|>"),
    (f"<|user|>\nGiven a positive integer n, find the smallest number of perfect squares that sum to n.\n<|assistant|>\ndef num_squares(n):\n    dp = [float('inf')] * (n + 1)\n    dp[0] = 0\n    for i in range(1, n + 1):\n        j = 1\n        while j * j <= i:\n            dp[i] = min(dp[i], 1 + dp[i - j*j])\n            j += 1\n    return dp[n]\n<|end|>"),
    # --- Intervals ---
    (f"<|user|>\nGiven an array of intervals, insert a new interval and merge if necessary.\n<|assistant|>\ndef insert_interval(intervals, new_interval):\n    res = []\n    i = 0\n    while i < len(intervals) and intervals[i][1] < new_interval[0]:\n        res.append(intervals[i])\n        i += 1\n    while i < len(intervals) and intervals[i][0] <= new_interval[1]:\n        new_interval[0] = min(new_interval[0], intervals[i][0])\n        new_interval[1] = max(new_interval[1], intervals[i][1])\n        i += 1\n    res.append(new_interval)\n    while i < len(intervals):\n        res.append(intervals[i])\n        i += 1\n    return res\n<|end|>"),
    (f"<|user|>\nGiven a list of intervals representing employee schedules, find the free time common to all.\n<|assistant|>\ndef employee_free_time(schedule):\n    intervals = sorted([i for emp in schedule for i in emp], key=lambda x: x[0])\n    res = []\n    end = intervals[0][1]\n    for s, e in intervals[1:]:\n        if s > end:\n            res.append([end, s])\n        end = max(end, e)\n    return res\n<|end|>"),
    # --- Matrix ---
    (f"<|user|>\nRotate a matrix by 90 degrees clockwise in-place.\n<|assistant|>\ndef rotate(matrix):\n    n = len(matrix)\n    for i in range(n):\n        for j in range(i, n):\n            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]\n    for i in range(n):\n        matrix[i].reverse()\n    return matrix\n<|end|>"),
    (f"<|user|>\nGiven a matrix, set entire row and column to zero if an element is zero.\n<|assistant|>\ndef set_zeroes(matrix):\n    R, C = len(matrix), len(matrix[0])\n    first_row = any(matrix[0][c] == 0 for c in range(C))\n    first_col = any(matrix[r][0] == 0 for r in range(R))\n    for r in range(1, R):\n        for c in range(1, C):\n            if matrix[r][c] == 0:\n                matrix[r][0] = 0\n                matrix[0][c] = 0\n    for r in range(1, R):\n        for c in range(1, C):\n            if matrix[r][0] == 0 or matrix[0][c] == 0:\n                matrix[r][c] = 0\n    if first_row:\n        for c in range(C):\n            matrix[0][c] = 0\n    if first_col:\n        for r in range(R):\n            matrix[r][0] = 0\n    return matrix\n<|end|>"),
    (f"<|user|>\nGiven a matrix of integers, return all elements in spiral order.\n<|assistant|>\ndef spiral_order(matrix):\n    if not matrix:\n        return []\n    res = []\n    t, b, l, r = 0, len(matrix) - 1, 0, len(matrix[0]) - 1\n    while t <= b and l <= r:\n        for j in range(l, r + 1):\n            res.append(matrix[t][j])\n        t += 1\n        for i in range(t, b + 1):\n            res.append(matrix[i][r])\n        r -= 1\n        if t <= b:\n            for j in range(r, l - 1, -1):\n                res.append(matrix[b][j])\n            b -= 1\n        if l <= r:\n            for i in range(b, t - 1, -1):\n                res.append(matrix[i][l])\n            l += 1\n    return res\n<|end|>"),
    (f"<|user|>\nSearch for a target value in a 2D matrix where rows and columns are sorted.\n<|assistant|>\ndef search_matrix(matrix, target):\n    if not matrix:\n        return False\n    r, c = 0, len(matrix[0]) - 1\n    while r < len(matrix) and c >= 0:\n        if matrix[r][c] == target:\n            return True\n        elif matrix[r][c] < target:\n            r += 1\n        else:\n            c -= 1\n    return False\n<|end|>"),
    # --- Strings ---
    (f"<|user|>\nGiven a string, find the first non-repeating character index or -1.\n<|assistant|>\ndef first_uniq_char(s):\n    counts = {}\n    for c in s:\n        counts[c] = counts.get(c, 0) + 1\n    for i, c in enumerate(s):\n        if counts[c] == 1:\n            return i\n    return -1\n<|end|>"),
    (f"<|user|>\nCompress a string using counts of repeated characters, modifying in-place.\n<|assistant|>\ndef compress(chars):\n    write = i = 0\n    while i < len(chars):\n        c = chars[i]\n        count = 0\n        while i < len(chars) and chars[i] == c:\n            i += 1\n            count += 1\n        chars[write] = c\n        write += 1\n        if count > 1:\n            for d in str(count):\n                chars[write] = d\n                write += 1\n    return write\n<|end|>"),
    (f"<|user|>\nCheck if two strings are one edit away (insert, delete, replace).\n<|assistant|>\ndef one_edit_away(s, t):\n    if abs(len(s) - len(t)) > 1:\n        return False\n    for i in range(min(len(s), len(t))):\n        if s[i] != t[i]:\n            if len(s) == len(t):\n                return s[i+1:] == t[i+1:]\n            elif len(s) < len(t):\n                return s[i:] == t[i+1:]\n            else:\n                return s[i+1:] == t[i:]\n    return True\n<|end|>"),
    (f"<|user|>\nGiven two strings s and t, return True if s is a subsequence of t.\n<|assistant|>\ndef is_subsequence(s, t):\n    it = iter(t)\n    return all(c in it for c in s)\n<|end|>"),
    (f"<|user|>\nGiven a string, reverse it word by word (trim leading/trailing spaces, reduce multiple spaces).\n<|assistant|>\ndef reverse_words(s):\n    return ' '.join(s.split()[::-1])\n<|end|>"),
    (f"<|user|>\nGiven a string, find the length of the last word.\n<|assistant|>\ndef length_of_last_word(s):\n    return len(s.strip().split(' ')[-1])\n<|end|>"),
    (f"<|user|>\nCheck if a given string is a valid palindrome ignoring non-alphanumeric characters.\n<|assistant|>\ndef is_palindrome_str(s):\n    l, r = 0, len(s) - 1\n    while l < r:\n        while l < r and not s[l].isalnum():\n            l += 1\n        while l < r and not s[r].isalnum():\n            r -= 1\n        if s[l].lower() != s[r].lower():\n            return False\n        l += 1\n        r -= 1\n    return True\n<|end|>"),
    (f"<|user|>\nGiven a pattern string and a string s, determine if s follows the same pattern.\n<|assistant|>\ndef word_pattern(pattern, s):\n    words = s.split()\n    if len(pattern) != len(words):\n        return False\n    p_to_w = {}\n    w_to_p = {}\n    for p, w in zip(pattern, words):\n        if p in p_to_w:\n            if p_to_w[p] != w:\n                return False\n        elif w in w_to_p:\n            return False\n        else:\n            p_to_w[p] = w\n            w_to_p[w] = p\n    return True\n<|end|>"),
    (f"<|user|>\nGiven a string s and an integer k, reverse the first k characters for every 2k segment.\n<|assistant|>\ndef reverse_str(s, k):\n    res = list(s)\n    for i in range(0, len(s), 2*k):\n        res[i:i+k] = reversed(res[i:i+k])\n    return ''.join(res)\n<|end|>"),
    (f"<|user|>\nGiven a string, return all substrings of length k with distinct characters.\n<|assistant|>\ndef distinct_substrings(s, k):\n    if len(s) < k:\n        return []\n    res = []\n    for i in range(len(s) - k + 1):\n        sub = s[i:i+k]\n        if len(set(sub)) == k:\n            res.append(sub)\n    return res\n<|end|>"),
    # --- Design ---
    (f"<|user|>\nDesign a HashMap without using built-in hash table libraries.\n<|assistant|>\nclass MyHashMap:\n    def __init__(self):\n        self.size = 1000\n        self.buckets = [[] for _ in range(self.size)]\n    def put(self, key, value):\n        h = key % self.size\n        for i, (k, v) in enumerate(self.buckets[h]):\n            if k == key:\n                self.buckets[h][i] = (key, value)\n                return\n        self.buckets[h].append((key, value))\n    def get(self, key):\n        h = key % self.size\n        for k, v in self.buckets[h]:\n            if k == key:\n                return v\n        return -1\n    def remove(self, key):\n        h = key % self.size\n        self.buckets[h] = [(k, v) for k, v in self.buckets[h] if k != key]\n<|end|>"),
    (f"<|user|>\nDesign a circular queue using arrays.\n<|assistant|>\nclass MyCircularQueue:\n    def __init__(self, k):\n        self.data = [0] * k\n        self.cap = k\n        self.head = self.tail = self.count = 0\n    def enQueue(self, value):\n        if self.isFull():\n            return False\n        self.data[self.tail] = value\n        self.tail = (self.tail + 1) % self.cap\n        self.count += 1\n        return True\n    def deQueue(self):\n        if self.isEmpty():\n            return False\n        self.head = (self.head + 1) % self.cap\n        self.count -= 1\n        return True\n    def Front(self):\n        return self.data[self.head] if not self.isEmpty() else -1\n    def Rear(self):\n        return self.data[(self.tail - 1) % self.cap] if not self.isEmpty() else -1\n    def isEmpty(self):\n        return self.count == 0\n    def isFull(self):\n        return self.count == self.cap\n<|end|>"),
    (f"<|user|>\nDesign a Least Recently Used (LRU) cache.\n<|assistant|>\nclass LRUCache:\n    def __init__(self, capacity):\n        self.cap = capacity\n        self.cache = {}\n        self.order = []\n    def get(self, key):\n        if key not in self.cache:\n            return -1\n        self.order.remove(key)\n        self.order.append(key)\n        return self.cache[key]\n    def put(self, key, value):\n        if key in self.cache:\n            self.order.remove(key)\n        elif len(self.cache) >= self.cap:\n            lru = self.order.pop(0)\n            del self.cache[lru]\n        self.cache[key] = value\n        self.order.append(key)\n<|end|>"),
    (f"<|user|>\nDesign a Logger that allows at most one message per 10 seconds.\n<|assistant|>\nclass Logger:\n    def __init__(self):\n        self.msg_time = {}\n    def shouldPrintMessage(self, timestamp, message):\n        if message in self.msg_time and timestamp - self.msg_time[message] < 10:\n            return False\n        self.msg_time[message] = timestamp\n        return True\n<|end|>"),
    (f"<|user|>\nDesign a time-based key-value store to retrieve values at different timestamps.\n<|assistant|>\nclass TimeMap:\n    def __init__(self):\n        self.store = {}\n    def set(self, key, value, timestamp):\n        if key not in self.store:\n            self.store[key] = []\n        self.store[key].append((timestamp, value))\n    def get(self, key, timestamp):\n        if key not in self.store:\n            return ''\n        pairs = self.store[key]\n        l, r = 0, len(pairs) - 1\n        while l <= r:\n            mid = (l + r) // 2\n            if pairs[mid][0] <= timestamp:\n                l = mid + 1\n            else:\n                r = mid - 1\n        return pairs[r][1] if r >= 0 else ''\n<|end|>"),
    # --- More Trees ---
    (f"<|user|>\nGiven a binary tree, find the maximum path sum (any node to any node).\n<|assistant|>\ndef max_path_sum(root):\n    best = float('-inf')\n    def gain(node):\n        nonlocal best\n        if not node:\n            return 0\n        left = max(gain(node.left), 0)\n        right = max(gain(node.right), 0)\n        best = max(best, node.val + left + right)\n        return node.val + max(left, right)\n    gain(root)\n    return best\n<|end|>"),
    (f"<|user|>\nGiven a binary tree, flatten it to a linked list in-place (preorder).\n<|assistant|>\ndef flatten(root):\n    cur = root\n    while cur:\n        if cur.left:\n            prev = cur.left\n            while prev.right:\n                prev = prev.right\n            prev.right = cur.right\n            cur.right = cur.left\n            cur.left = None\n        cur = cur.right\n<|end|>"),
    (f"<|user|>\nGiven the root of a binary tree, return the zigzag level order traversal.\n<|assistant|>\ndef zigzag_level_order(root):\n    if not root:\n        return []\n    res, q = [], [root]\n    left_to_right = True\n    while q:\n        level = []\n        for _ in range(len(q)):\n            node = q.pop(0)\n            level.append(node.val)\n            if node.left:\n                q.append(node.left)\n            if node.right:\n                q.append(node.right)\n        if not left_to_right:\n            level.reverse()\n        res.append(level)\n        left_to_right = not left_to_right\n    return res\n<|end|>"),
    (f"<|user|>\nGiven a binary tree, find the sum of all left leaves.\n<|assistant|>\ndef sum_of_left_leaves(root):\n    def dfs(node, is_left):\n        if not node:\n            return 0\n        if not node.left and not node.right and is_left:\n            return node.val\n        return dfs(node.left, True) + dfs(node.right, False)\n    return dfs(root, False)\n<|end|>"),
    (f"<|user|>\nGiven a binary tree, find its minimum depth.\n<|assistant|>\ndef min_depth(root):\n    if not root:\n        return 0\n    if not root.left:\n        return 1 + min_depth(root.right)\n    if not root.right:\n        return 1 + min_depth(root.left)\n    return 1 + min(min_depth(root.left), min_depth(root.right))\n<|end|>"),
    (f"<|user|>\nGiven a binary tree, return the right side view.\n<|assistant|>\ndef right_side_view(root):\n    if not root:\n        return []\n    res = []\n    q = [root]\n    while q:\n        for i in range(len(q)):\n            node = q.pop(0)\n            if i == 0:\n                res.append(node.val)\n            if node.right:\n                q.append(node.right)\n            if node.left:\n                q.append(node.left)\n    return res\n<|end|>"),
    (f"<|user|>\nGiven a binary tree, find all root-to-leaf paths.\n<|assistant|>\ndef binary_tree_paths(root):\n    if not root:\n        return []\n    res = []\n    def dfs(node, path):\n        if not node.left and not node.right:\n            res.append(path + str(node.val))\n            return\n        if node.left:\n            dfs(node.left, path + str(node.val) + '->')\n        if node.right:\n            dfs(node.right, path + str(node.val) + '->')\n    dfs(root, '')\n    return res\n<|end|>"),
    (f"<|user|>\nGiven a binary tree where each node has a digit, sum all root-to-leaf numbers.\n<|assistant|>\ndef sum_numbers(root):\n    def dfs(node, cur):\n        if not node:\n            return 0\n        cur = cur * 10 + node.val\n        if not node.left and not node.right:\n            return cur\n        return dfs(node.left, cur) + dfs(node.right, cur)\n    return dfs(root, 0)\n<|end|>"),
    # --- More Graphs ---
    (f"<|user|>\nGiven a 2D grid of characters and a word, return True if the word exists (adjacent cells).\n<|assistant|>\ndef exist(board, word):\n    R, C = len(board), len(board[0])\n    def dfs(r, c, i):\n        if i == len(word):\n            return True\n        if r < 0 or r >= R or c < 0 or c >= C or board[r][c] != word[i]:\n            return False\n        tmp, board[r][c] = board[r][c], '#'\n        found = any(dfs(r+dr, c+dc, i+1) for dr, dc in [(1,0),(-1,0),(0,1),(0,-1)])\n        board[r][c] = tmp\n        return found\n    for r in range(R):\n        for c in range(C):\n            if dfs(r, c, 0):\n                return True\n    return False\n<|end|>"),
    (f"<|user|>\nGiven an undirected graph with n nodes labeled 0..n-1 and edges, count the number of connected components.\n<|assistant|>\ndef count_components(n, edges):\n    parent = list(range(n))\n    def find(x):\n        while parent[x] != x:\n            parent[x] = parent[parent[x]]\n            x = parent[x]\n        return x\n    def union(x, y):\n        rx, ry = find(x), find(y)\n        if rx != ry:\n            parent[ry] = rx\n            return True\n        return False\n    for u, v in edges:\n        union(u, v)\n    return len({find(i) for i in range(n)})\n<|end|>"),
    (f"<|user|>\nGiven n nodes and edges, determine if the graph is a valid tree (connected and no cycles).\n<|assistant|>\ndef valid_tree(n, edges):\n    if len(edges) != n - 1:\n        return False\n    parent = list(range(n))\n    def find(x):\n        while parent[x] != x:\n            parent[x] = parent[parent[x]]\n            x = parent[x]\n        return x\n    def union(x, y):\n        rx, ry = find(x), find(y)\n        if rx == ry:\n            return False\n        parent[ry] = rx\n        return True\n    for u, v in edges:\n        if not union(u, v):\n            return False\n    return True\n<|end|>"),
    (f"<|user|>\nGiven a 2D grid, find the size of the largest connected region of 1s.\n<|assistant|>\ndef max_area_island(grid):\n    R, C = len(grid), len(grid[0])\n    best = 0\n    def dfs(r, c):\n        if r < 0 or r >= R or c < 0 or c >= C or grid[r][c] == 0:\n            return 0\n        grid[r][c] = 0\n        return 1 + dfs(r+1,c) + dfs(r-1,c) + dfs(r,c+1) + dfs(r,c-1)\n    for r in range(R):\n        for c in range(C):\n            if grid[r][c] == 1:\n                best = max(best, dfs(r, c))\n    return best\n<|end|>"),
    (f"<|user|>\nGiven edges of a directed graph, find the minimum number of edges to reverse to reach target.\n<|assistant|>\ndef min_reorder(n, connections):\n    graph = [[] for _ in range(n)]\n    for a, b in connections:\n        graph[a].append((b, 0))\n        graph[b].append((a, 1))\n    q = [0]\n    visited = {0}\n    changes = 0\n    while q:\n        u = q.pop(0)\n        for v, cost in graph[u]:\n            if v not in visited:\n                visited.add(v)\n                changes += cost\n                q.append(v)\n    return changes\n<|end|>"),
    # --- More DP ---
    (f"<|user|>\nGiven an array of integers, find if there exists a subset that sums to a target.\n<|assistant|>\ndef can_partition(nums, target):\n    dp = [False] * (target + 1)\n    dp[0] = True\n    for n in nums:\n        for s in range(target, n - 1, -1):\n            if dp[s - n]:\n                dp[s] = True\n    return dp[target]\n<|end|>"),
    (f"<|user|>\nGiven a non-empty array containing only positive integers, partition it into two subsets with equal sum.\n<|assistant|>\ndef can_partition_equal(nums):\n    total = sum(nums)\n    if total % 2:\n        return False\n    target = total // 2\n    dp = [False] * (target + 1)\n    dp[0] = True\n    for n in nums:\n        for s in range(target, n - 1, -1):\n            if dp[s - n]:\n                dp[s] = True\n    return dp[target]\n<|end|>"),
    (f"<|user|>\nGiven an array, find the maximum sum of a subsequence where no two elements are adjacent.\n<|assistant|>\ndef max_sum_non_adjacent(nums):\n    incl = excl = 0\n    for n in nums:\n        new_incl = excl + n\n        excl = max(incl, excl)\n        incl = new_incl\n    return max(incl, excl)\n<|end|>"),
    (f"<|user|>\nGiven a string s, return the length of the longest palindromic subsequence.\n<|assistant|>\ndef longest_palindrome_subseq(s):\n    n = len(s)\n    dp = [[0] * n for _ in range(n)]\n    for i in range(n - 1, -1, -1):\n        dp[i][i] = 1\n        for j in range(i + 1, n):\n            if s[i] == s[j]:\n                dp[i][j] = 2 + dp[i+1][j-1]\n            else:\n                dp[i][j] = max(dp[i+1][j], dp[i][j-1])\n    return dp[0][n-1]\n<|end|>"),
    (f"<|user|>\nGiven a m x n grid with non-negative numbers, find a path from top-left to bottom-right minimizing sum.\n<|assistant|>\ndef min_path_sum(grid):\n    m, n = len(grid), len(grid[0])\n    dp = [float('inf')] * n\n    dp[0] = 0\n    for r in range(m):\n        dp[0] += grid[r][0]\n        for c in range(1, n):\n            if r == 0:\n                dp[c] = dp[c-1] + grid[r][c]\n            else:\n                dp[c] = grid[r][c] + min(dp[c], dp[c-1])\n    return dp[-1]\n<|end|>"),
    (f"<|user|>\nGiven a string and a list of words, return the minimum number of extra characters left after breaking the string.\n<|assistant|>\ndef min_extra_char(s, dictionary):\n    words = set(dictionary)\n    n = len(s)\n    dp = [0] + [float('inf')] * n\n    for i in range(1, n + 1):\n        dp[i] = dp[i-1] + 1\n        for j in range(i):\n            if s[j:i] in words:\n                dp[i] = min(dp[i], dp[j])\n    return dp[n]\n<|end|>"),
    (f"<|user|>\nGiven a 2D binary matrix, find the largest rectangle containing only 1s.\n<|assistant|>\ndef maximal_rectangle(matrix):\n    if not matrix:\n        return 0\n    heights = [0] * len(matrix[0])\n    best = 0\n    for row in matrix:\n        for i, c in enumerate(row):\n            heights[i] = heights[i] + 1 if c == '1' else 0\n        stack = []\n        for i, h in enumerate(heights + [0]):\n            while stack and heights[stack[-1]] > h:\n                height = heights[stack.pop()]\n                width = i if not stack else i - stack[-1] - 1\n                best = max(best, height * width)\n            stack.append(i)\n    return best\n<|end|>"),
    (f"<|user|>\nGiven a list of numbers, find the length of the longest increasing path in a matrix.\n<|assistant|>\ndef longest_increasing_path(matrix):\n    if not matrix:\n        return 0\n    R, C = len(matrix), len(matrix[0])\n    memo = [[0] * C for _ in range(R)]\n    def dfs(r, c):\n        if memo[r][c]:\n            return memo[r][c]\n        best = 1\n        for dr, dc in [(1,0),(-1,0),(0,1),(0,-1)]:\n            nr, nc = r+dr, c+dc\n            if 0 <= nr < R and 0 <= nc < C and matrix[nr][nc] > matrix[r][c]:\n                best = max(best, 1 + dfs(nr, nc))\n        memo[r][c] = best\n        return best\n    return max(dfs(r, c) for r in range(R) for c in range(C))\n<|end|>"),
    # --- Sorting & Searching ---
    (f"<|user|>\nFind the k-th smallest element in a sorted matrix (each row and column sorted).\n<|assistant|>\ndef kth_smallest_matrix(matrix, k):\n    n = len(matrix)\n    lo, hi = matrix[0][0], matrix[n-1][n-1]\n    while lo < hi:\n        mid = (lo + hi) // 2\n        count = 0\n        for row in matrix:\n            count += sum(1 for x in row if x <= mid)\n        if count < k:\n            lo = mid + 1\n        else:\n            hi = mid\n    return lo\n<|end|>"),
    (f"<|user|>\nSort an array of 0s, 1s, and 2s in-place (Dutch flag problem).\n<|assistant|>\ndef sort_colors(nums):\n    l, m, r = 0, 0, len(nums) - 1\n    while m <= r:\n        if nums[m] == 0:\n            nums[l], nums[m] = nums[m], nums[l]\n            l += 1\n            m += 1\n        elif nums[m] == 1:\n            m += 1\n        else:\n            nums[m], nums[r] = nums[r], nums[m]\n            r -= 1\n    return nums\n<|end|>"),
    (f"<|user|>\nFind the peak element in an array (greater than neighbors).\n<|assistant|>\ndef find_peak_element(nums):\n    l, r = 0, len(nums) - 1\n    while l < r:\n        mid = (l + r) // 2\n        if nums[mid] > nums[mid + 1]:\n            r = mid\n        else:\n            l = mid + 1\n    return l\n<|end|>"),
    (f"<|user|>\nGiven two sorted arrays, find the median of the combined array in O(log(m+n)).\n<|assistant|>\ndef find_median_sorted_arrays(a, b):\n    if len(a) > len(b):\n        a, b = b, a\n    m, n = len(a), len(b)\n    lo, hi = 0, m\n    while lo <= hi:\n        i = (lo + hi) // 2\n        j = (m + n + 1) // 2 - i\n        a_left = a[i-1] if i > 0 else float('-inf')\n        a_right = a[i] if i < m else float('inf')\n        b_left = b[j-1] if j > 0 else float('-inf')\n        b_right = b[j] if j < n else float('inf')\n        if a_left <= b_right and b_left <= a_right:\n            if (m + n) % 2:\n                return max(a_left, b_left)\n            return (max(a_left, b_left) + min(a_right, b_right)) / 2\n        elif a_left > b_right:\n            hi = i - 1\n        else:\n            lo = i + 1\n    return 0\n<|end|>"),
    (f"<|user|>\nGiven a list of integers, find all pairs with a given sum.\n<|assistant|>\ndef pair_sum(nums, target):\n    seen = set()\n    res = []\n    for n in nums:\n        comp = target - n\n        if comp in seen:\n            res.append((comp, n))\n        seen.add(n)\n    return res\n<|end|>"),
    (f"<|user|>\nGiven an array, find the smallest missing positive integer.\n<|assistant|>\ndef first_missing_positive(nums):\n    n = len(nums)\n    for i in range(n):\n        while 1 <= nums[i] <= n and nums[nums[i] - 1] != nums[i]:\n            nums[nums[i] - 1], nums[i] = nums[i], nums[nums[i] - 1]\n    for i in range(n):\n        if nums[i] != i + 1:\n            return i + 1\n    return n + 1\n<|end|>"),
    # --- More String Manipulation ---
    (f"<|user|>\nGiven a string, find the longest common prefix among an array of strings.\n<|assistant|>\ndef longest_common_prefix(strs):\n    if not strs:\n        return ''\n    for i in range(len(strs[0])):\n        for s in strs[1:]:\n            if i >= len(s) or s[i] != strs[0][i]:\n                return strs[0][:i]\n    return strs[0]\n<|end|>"),
    (f"<|user|>\nGiven a string, convert it to integer (atoi) handling whitespace, sign, and overflow.\n<|assistant|>\ndef my_atoi(s):\n    s = s.lstrip()\n    if not s:\n        return 0\n    sign = 1\n    i = 0\n    if s[i] in '+-':\n        sign = -1 if s[i] == '-' else 1\n        i += 1\n    res = 0\n    while i < len(s) and s[i].isdigit():\n        res = res * 10 + int(s[i])\n        i += 1\n    res *= sign\n    if res < -2**31:\n        return -2**31\n    if res > 2**31 - 1:\n        return 2**31 - 1\n    return res\n<|end|>"),
    (f"<|user|>\nGiven two strings, return True if they are isomorphic (character mapping).\n<|assistant|>\ndef is_isomorphic(s, t):\n    if len(s) != len(t):\n        return False\n    s_to_t = {}\n    t_to_s = {}\n    for cs, ct in zip(s, t):\n        if cs in s_to_t:\n            if s_to_t[cs] != ct:\n                return False\n        elif ct in t_to_s:\n            return False\n        else:\n            s_to_t[cs] = ct\n            t_to_s[ct] = cs\n    return True\n<|end|>"),
    (f"<|user|>\nGiven a URL, return the domain name (extract host).\n<|assistant|>\ndef extract_domain(url):\n    from urllib.parse import urlparse\n    parsed = urlparse(url)\n    return parsed.netloc or parsed.path.split('/')[0]\n<|end|>"),
    (f"<|user|>\nGiven a string, find all unique palindromic substrings.\n<|assistant|>\ndef palindromic_substrings(s):\n    res = set()\n    for i in range(len(s)):\n        for l, r in [(i, i), (i, i+1)]:\n            while l >= 0 and r < len(s) and s[l] == s[r]:\n                res.add(s[l:r+1])\n                l -= 1\n                r += 1\n    return list(res)\n<|end|>"),
    # --- More Math ---
    (f"<|user|>\nGiven a positive integer, return its Roman numeral representation.\n<|assistant|>\ndef int_to_roman(num):\n    vals = [(1000,'M'),(900,'CM'),(500,'D'),(400,'CD'),(100,'C'),(90,'XC'),(50,'L'),(40,'XL'),(10,'X'),(9,'IX'),(5,'V'),(4,'IV'),(1,'I')]\n    res = ''\n    for val, sym in vals:\n        while num >= val:\n            res += sym\n            num -= val\n    return res\n<|end|>"),
    (f"<|user|>\nGiven a Roman numeral, convert it to an integer.\n<|assistant|>\ndef roman_to_int(s):\n    vals = {'I':1,'V':5,'X':10,'L':50,'C':100,'D':500,'M':1000}\n    res = 0\n    for i in range(len(s)):\n        if i + 1 < len(s) and vals[s[i]] < vals[s[i+1]]:\n            res -= vals[s[i]]\n        else:\n            res += vals[s[i]]\n    return res\n<|end|>"),
    (f"<|user|>\nGiven an integer n, return the n-th ugly number (only prime factors 2, 3, 5).\n<|assistant|>\ndef nth_ugly_number(n):\n    nums = [1]\n    i2 = i3 = i5 = 0\n    for _ in range(1, n):\n        next_u = min(nums[i2]*2, nums[i3]*3, nums[i5]*5)\n        nums.append(next_u)\n        if next_u == nums[i2]*2:\n            i2 += 1\n        if next_u == nums[i3]*3:\n            i3 += 1\n        if next_u == nums[i5]*5:\n            i5 += 1\n    return nums[-1]\n<|end|>"),
    (f"<|user|>\nGiven a non-negative integer n, return all numbers from 1 to n in lexicographical order.\n<|assistant|>\ndef lexical_order(n):\n    res = []\n    cur = 1\n    for _ in range(n):\n        res.append(cur)\n        if cur * 10 <= n:\n            cur *= 10\n        else:\n            while cur % 10 == 9 or cur + 1 > n:\n                cur //= 10\n            cur += 1\n    return res\n<|end|>"),
    (f"<|user|>\nGiven an integer n, return Trailing zeroes in n!.\n<|assistant|>\ndef trailing_zeroes(n):\n    count = 0\n    while n:\n        n //= 5\n        count += n\n    return count\n<|end|>"),
    # --- More Design ---
    (f"<|user|>\nDesign a stack that supports increment operation on bottom k elements.\n<|assistant|>\nclass CustomStack:\n    def __init__(self, maxSize):\n        self.stack = []\n        self.maxSize = maxSize\n    def push(self, x):\n        if len(self.stack) < self.maxSize:\n            self.stack.append(x)\n    def pop(self):\n        return self.stack.pop() if self.stack else -1\n    def increment(self, k, val):\n        for i in range(min(k, len(self.stack))):\n            self.stack[i] += val\n<|end|>"),
    (f"<|user|>\nDesign a hit counter that counts hits in the last 5 minutes.\n<|assistant|>\nclass HitCounter:\n    def __init__(self):\n        self.hits = []\n    def hit(self, timestamp):\n        self.hits.append(timestamp)\n    def getHits(self, timestamp):\n        while self.hits and self.hits[0] <= timestamp - 300:\n            self.hits.pop(0)\n        return len(self.hits)\n<|end|>"),
    # --- More Backtracking ---
    (f"<|user|>\nGiven a string of digits, return all possible IP addresses.\n<|assistant|>\ndef restore_ip_addresses(s):\n    res = []\n    def backtrack(start, path):\n        if len(path) == 4:\n            if start == len(s):\n                res.append('.'.join(path))\n            return\n        for i in range(1, 4):\n            if start + i > len(s):\n                break\n            seg = s[start:start+i]\n            if (seg[0] == '0' and len(seg) > 1) or int(seg) > 255:\n                continue\n            backtrack(start + i, path + [seg])\n    backtrack(0, [])\n    return res\n<|end|>"),
    (f"<|user|>\nGiven a collection of numbers, find all unique subsets that may contain duplicates.\n<|assistant|>\ndef subsets_with_dup(nums):\n    nums.sort()\n    res = [[]]\n    last_count = 0\n    for i in range(len(nums)):\n        start = last_count if i > 0 and nums[i] == nums[i-1] else 0\n        last_count = len(res)\n        for j in range(start, last_count):\n            res.append(res[j] + [nums[i]])\n    return res\n<|end|>"),
    # --- More Arrays ---
    (f"<|user|>\nGiven an array of integers, find the maximum difference between two elements where larger comes after smaller.\n<|assistant|>\ndef max_diff(nums):\n    min_so_far = float('inf')\n    diff = -1\n    for n in nums:\n        if n < min_so_far:\n            min_so_far = n\n        elif n - min_so_far > diff:\n            diff = n - min_so_far\n    return diff\n<|end|>"),
    (f"<|user|>\nGiven an array and a target, find the number of pairs with difference equal to target.\n<|assistant|>\ndef pairs_with_diff(nums, k):\n    seen = set()\n    count = 0\n    for n in nums:\n        if n - k in seen:\n            count += 1\n        if n + k in seen:\n            count += 1\n        seen.add(n)\n    return count\n<|end|>"),
    (f"<|user|>\nGiven an array, find the maximum product subarray.\n<|assistant|>\ndef max_product_subarray(nums):\n    best = cur_min = cur_max = nums[0]\n    for n in nums[1:]:\n        candidates = (n, cur_max * n, cur_min * n)\n        cur_max = max(candidates)\n        cur_min = min(candidates)\n        best = max(best, cur_max)\n    return best\n<|end|>"),
    (f"<|user|>\nGiven an array, find the shortest subarray to remove to make the array sorted.\n<|assistant|>\ndef find_length_of_shortest_subarray(nums):\n    n = len(nums)\n    l, r = 0, n - 1\n    while l < n - 1 and nums[l] <= nums[l+1]:\n        l += 1\n    if l == n - 1:\n        return 0\n    while r > 0 and nums[r-1] <= nums[r]:\n        r -= 1\n    res = min(n - l - 1, r)\n    i, j = 0, r\n    while i <= l and j < n:\n        if nums[i] <= nums[j]:\n            res = min(res, j - i - 1)\n            i += 1\n        else:\n            j += 1\n    return res\n<|end|>"),
    (f"<|user|>\nGiven an array of points, find all points that lie on the same line (max points on a line).\n<|assistant|>\ndef max_points(points):\n    n = len(points)\n    if n < 3:\n        return n\n    best = 0\n    for i in range(n):\n        slopes = {}\n        same = 1\n        for j in range(i + 1, n):\n            dx = points[j][0] - points[i][0]\n            dy = points[j][1] - points[i][1]\n            if dx == 0 and dy == 0:\n                same += 1\n                continue\n            g = __import__('math').gcd(dx, dy)\n            dx //= g\n            dy //= g\n            key = (dx, dy)\n            slopes[key] = slopes.get(key, 0) + 1\n        best = max(best, (max(slopes.values()) if slopes else 0) + same)\n    return best\n<|end|>"),
    # --- More Tree ---
    (f"<|user|>\nConvert a binary search tree to a sorted doubly linked list in-place.\n<|assistant|>\ndef tree_to_doubly_list(root):\n    if not root:\n        return None\n    def dfs(node):\n        nonlocal first, last\n        if not node:\n            return\n        dfs(node.left)\n        if last:\n            last.right = node\n            node.left = last\n        else:\n            first = node\n        last = node\n        dfs(node.right)\n    first = last = None\n    dfs(root)\n    first.left = last\n    last.right = first\n    return first\n<|end|>"),
    (f"<|user|>\nGiven a binary tree, find the k-th smallest element in a BST.\n<|assistant|>\ndef kth_smallest(root, k):\n    stack = []\n    cur = root\n    while cur or stack:\n        while cur:\n            stack.append(cur)\n            cur = cur.left\n        cur = stack.pop()\n        k -= 1\n        if k == 0:\n            return cur.val\n        cur = cur.right\n    return -1\n<|end|>"),
    (f"<|user|>\nGiven a binary search tree, find the inorder successor of a given node.\n<|assistant|>\ndef inorder_successor(root, p):\n    successor = None\n    while root:\n        if p.val < root.val:\n            successor = root\n            root = root.left\n        else:\n            root = root.right\n    return successor\n<|end|>"),
    # --- Greedy ---
    (f"<|user|>\nGiven an array of gas costs and distances, find the starting station to complete a circuit.\n<|assistant|>\ndef can_complete_circuit(gas, cost):\n    total = cur = start = 0\n    for i in range(len(gas)):\n        diff = gas[i] - cost[i]\n        total += diff\n        cur += diff\n        if cur < 0:\n            start = i + 1\n            cur = 0\n    return start if total >= 0 else -1\n<|end|>"),
    (f"<|user|>\nGiven n, partition it into at least two positive integers that maximize the product.\n<|assistant|>\ndef integer_break(n):\n    if n <= 3:\n        return n - 1\n    q, r = divmod(n, 3)\n    if r == 0:\n        return 3 ** q\n    if r == 1:\n        return 3 ** (q - 1) * 4\n    return 3 ** q * 2\n<|end|>"),
    (f"<|user|>\nGiven an array of strings, find the longest string that can be formed by concatenating array elements.\n<|assistant|>\ndef longest_word(words):\n    words.sort(key=lambda x: (-len(x), x))\n    word_set = set(words)\n    for w in words:\n        word_set.remove(w)\n        if all(w[:i] in word_set for i in range(1, len(w))):\n            return w\n        word_set.add(w)\n    return ''\n<|end|>"),
]

# Remove duplicates by comparing with existing content
existing_set = set(texts)
for t in new_samples:
    if t not in existing_set:
        texts.append(t)
        existing_set.add(t)

print(f"Added {len(texts) - 240} new samples. Total: {len(texts)}")
pickle.dump(texts, open(path, "wb"))
print("Saved successfully.")
