"""
Generate synthetic code+reasoning training data using the teacher (this LLM).
Saved as pickle in dataset_cache/ for training.

Run: python synthetic_data.py
"""

import pickle
from pathlib import Path

CACHE = Path("dataset_cache")
CACHE.mkdir(exist_ok=True)

# Each sample: {problem, reasoning, code}
# Format: <|user|>\n{problem}\n<|reasoning|>\n{reasoning}\n<|assistant|>\n{code}\n<|end|>
SAMPLES = [
    # ── Arrays & Hashing ──
    {"problem": "Given an array of integers nums and an integer target, return indices of the two numbers that add up to target.", "reasoning": "Use a hash map to store each number's index as we iterate. For each num, compute complement = target - num. If complement exists in map, return [map[complement], i]. This gives O(n) time and O(n) space.", "code": "def two_sum(nums: list[int], target: int) -> list[int]:\n    seen = {}\n    for i, n in enumerate(nums):\n        c = target - n\n        if c in seen:\n            return [seen[c], i]\n        seen[n] = i"},
    {"problem": "Given an array, group anagrams together.", "reasoning": "Each anagram has the same sorted string. Use a dict where key = sorted string, value = list of original strings. Iterate over words, sort each, append to dict. Return dict values. Time O(n * k log k) where k is max word length.", "code": "def group_anagrams(strs: list[str]) -> list[list[str]]:\n    groups = {}\n    for s in strs:\n        key = ''.join(sorted(s))\n        groups.setdefault(key, []).append(s)\n    return list(groups.values())"},
    {"problem": "Given an array, find the longest consecutive sequence of integers (not necessarily contiguous in the array).", "reasoning": "Insert all numbers into a set for O(1) lookups. Iterate and for each number, check if num-1 exists to find sequence starts. If it's a start, count consecutive elements by checking num+1, num+2 etc. Track max length. O(n) time.", "code": "def longest_consecutive(nums: list[int]) -> int:\n    s = set(nums)\n    best = 0\n    for n in s:\n        if n - 1 not in s:\n            length = 1\n            while n + length in s:\n                length += 1\n            best = max(best, length)\n    return best"},
    # ── Two Pointers ──
    {"problem": "Given an integer array, move all zeros to the end while maintaining the relative order of non-zero elements.", "reasoning": "Use two pointers: slow pointer pos tracks where to place the next non-zero. Iterate fast pointer through array. When nums[fast] != 0, swap nums[pos] and nums[fast], increment pos. O(n) time, O(1) space.", "code": "def move_zeroes(nums: list[int]) -> None:\n    pos = 0\n    for i in range(len(nums)):\n        if nums[i] != 0:\n            nums[pos], nums[i] = nums[i], nums[pos]\n            pos += 1"},
    {"problem": "Given a string of parentheses, determine if it's valid (every open bracket has matching close in correct order).", "reasoning": "Use a stack. Push opening brackets. When we see a closing bracket, check if stack is empty or top doesn't match. If mismatch, return False. At end, return True if stack is empty. O(n) time and space.", "code": "def is_valid(s: str) -> bool:\n    pairs = {')': '(', '}': '{', ']': '['}\n    stack = []\n    for c in s:\n        if c in pairs:\n            if not stack or stack.pop() != pairs[c]:\n                return False\n        else:\n            stack.append(c)\n    return not stack"},
    # ── Sliding Window ──
    {"problem": "Given two strings s and p, return all start indices of p's anagrams in s.", "reasoning": "Use a fixed-size sliding window with character frequency counter. Build counter for p. Slide window of len(p) over s, updating counter. When window counter matches p counter, record start index. O(n) time.", "code": "def find_anagrams(s: str, p: str) -> list[int]:\n    from collections import Counter\n    need = Counter(p)\n    have = Counter()\n    res = []\n    for i, c in enumerate(s):\n        have[c] += 1\n        if i >= len(p):\n            if have[s[i - len(p)]] == 1:\n                del have[s[i - len(p)]]\n            else:\n                have[s[i - len(p)]] -= 1\n        if have == need:\n            res.append(i - len(p) + 1)\n    return res"},
    # ── Stack / Monotonic ──
    {"problem": "Given temperatures, return an array where answer[i] is the number of days until a warmer temperature.", "reasoning": "Monotonic decreasing stack. Iterate temperatures. While stack not empty and current temp > stack top temp, pop index and set result[popped] = i - popped. Push current index. O(n) time.", "code": "def daily_temperatures(temps: list[int]) -> list[int]:\n    res = [0] * len(temps)\n    stack = []\n    for i, t in enumerate(temps):\n        while stack and t > temps[stack[-1]]:\n            idx = stack.pop()\n            res[idx] = i - idx\n        stack.append(i)\n    return res"},
    # ── Binary Search ──
    {"problem": "Find the minimum in a rotated sorted array.", "reasoning": "Modified binary search. If nums[l] < nums[r], array is not rotated, return nums[l]. Otherwise, check mid. If nums[mid] >= nums[l], min is in right half (l = mid + 1). Else min is in left half (r = mid). O(log n).", "code": "def find_min(nums: list[int]) -> int:\n    l, r = 0, len(nums) - 1\n    while l < r:\n        if nums[l] < nums[r]:\n            return nums[l]\n        mid = (l + r) // 2\n        if nums[mid] >= nums[l]:\n            l = mid + 1\n        else:\n            r = mid\n    return nums[l]"},
    {"problem": "Search for a target in a rotated sorted array.", "reasoning": "Binary search with rotation detection. Find mid. One half is always sorted. If nums[l] <= nums[mid], left is sorted. Check if target in left range, else search right. Vice versa for right-sorted case. O(log n).", "code": "def search_rotated(nums: list[int], target: int) -> int:\n    l, r = 0, len(nums) - 1\n    while l <= r:\n        mid = (l + r) // 2\n        if nums[mid] == target:\n            return mid\n        if nums[l] <= nums[mid]:\n            if nums[l] <= target < nums[mid]:\n                r = mid - 1\n            else:\n                l = mid + 1\n        else:\n            if nums[mid] < target <= nums[r]:\n                l = mid + 1\n            else:\n                r = mid - 1\n    return -1"},
    # ── Linked List ──
    {"problem": "Reverse a singly linked list.", "reasoning": "Iterative: maintain prev=None, curr=head. At each step, save curr.next, point curr.next to prev, move prev=curr, curr=next. Return prev as new head. O(n) time, O(1) space.", "code": "def reverse_list(head):\n    prev = None\n    curr = head\n    while curr:\n        nxt = curr.next\n        curr.next = prev\n        prev = curr\n        curr = nxt\n    return prev"},
    {"problem": "Merge two sorted linked lists into one sorted list.", "reasoning": "Use a dummy head. Compare l1.val and l2.val, append smaller to result. Advance that list. When one list empties, append the other. O(n + m) time.", "code": "def merge_two_lists(l1, l2):\n    dummy = tail = ListNode()\n    while l1 and l2:\n        if l1.val < l2.val:\n            tail.next, l1 = l1, l1.next\n        else:\n            tail.next, l2 = l2, l2.next\n        tail = tail.next\n    tail.next = l1 or l2\n    return dummy.next"},
    {"problem": "Detect cycle in a linked list.", "reasoning": "Floyd's tortoise and hare. Slow moves 1 step, fast moves 2 steps. If they meet, cycle exists. If fast reaches None, no cycle. O(n) time, O(1) space.", "code": "def has_cycle(head) -> bool:\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow == fast:\n            return True\n    return False"},
    # ── Trees ──
    {"problem": "Find the maximum depth of a binary tree.", "reasoning": "Recursive DFS. Base case: if node is None, return 0. Otherwise return 1 + max(depth(left), depth(right)). O(n) time, O(h) space for recursion.", "code": "def max_depth(root) -> int:\n    if not root:\n        return 0\n    return 1 + max(max_depth(root.left), max_depth(root.right))"},
    {"problem": "Check if a binary tree is symmetric (mirror of itself).", "reasoning": "Recursive helper that takes left and right nodes. Both None -> True. One None -> False. Values differ -> False. Otherwise recurse on (left.left, right.right) and (left.right, right.left). O(n).", "code": "def is_symmetric(root) -> bool:\n    def same(l, r):\n        if not l and not r:\n            return True\n        if not l or not r or l.val != r.val:\n            return False\n        return same(l.left, r.right) and same(l.right, r.left)\n    return same(root.left, root.right) if root else True"},
    {"problem": "Given a binary tree, return its level-order traversal (BFS).", "reasoning": "Use a queue. Start with root. While queue not empty, process all nodes at current level: pop each, add val to level list, push children. Append level list to result. O(n) time and space.", "code": "def level_order(root) -> list[list[int]]:\n    from collections import deque\n    if not root:\n        return []\n    q = deque([root])\n    res = []\n    while q:\n        level = []\n        for _ in range(len(q)):\n            node = q.popleft()\n            level.append(node.val)\n            if node.left: q.append(node.left)\n            if node.right: q.append(node.right)\n        res.append(level)\n    return res"},
    {"problem": "Check if a binary tree is a valid BST.", "reasoning": "In-order traversal of a BST should be strictly increasing. Recursively traverse with lower/upper bounds. For root, allow any value. For left child, upper bound = root.val. For right child, lower bound = root.val. O(n).", "code": "def is_valid_bst(root, lo=float('-inf'), hi=float('inf')) -> bool:\n    if not root:\n        return True\n    if root.val <= lo or root.val >= hi:\n        return False\n    return is_valid_bst(root.left, lo, root.val) and is_valid_bst(root.right, root.val, hi)"},
    # ── Tries ──
    {"problem": "Implement a Trie with insert, search, and startsWith.", "reasoning": "Each node has a dict of children and a flag for end of word. Insert: traverse/create nodes for each char, mark last as end. Search: traverse chars, check end flag at end. StartsWith: traverse chars, return True if reachable. O(k) per operation.", "code": "class Trie:\n    def __init__(self):\n        self.children = {}\n        self.end = False\n    def insert(self, word: str) -> None:\n        node = self\n        for c in word:\n            node = node.children.setdefault(c, Trie())\n        node.end = True\n    def search(self, word: str) -> bool:\n        node = self\n        for c in word:\n            if c not in node.children:\n                return False\n            node = node.children[c]\n        return node.end\n    def starts_with(self, prefix: str) -> bool:\n        node = self\n        for c in prefix:\n            if c not in node.children:\n                return False\n            node = node.children[c]\n        return True"},
    # ── Backtracking ──
    {"problem": "Given a set of distinct integers, return all possible subsets (the power set).", "reasoning": "Backtracking. At each index, we have two choices: include nums[i] or skip. Recurse to next index. When i == len(nums), add current subset to result. O(2^n) time.", "code": "def subsets(nums: list[int]) -> list[list[int]]:\n    res = []\n    def backtrack(i, path):\n        if i == len(nums):\n            res.append(path[:])\n            return\n        backtrack(i + 1, path)\n        path.append(nums[i])\n        backtrack(i + 1, path)\n        path.pop()\n    backtrack(0, [])\n    return res"},
    {"problem": "Given a phone keypad mapping, return all possible letter combinations for a digit string.", "reasoning": "Backtracking with mapping. Map digits to letters. Build combinations recursively: for each letter of current digit, append, recurse to next digit, backtrack. When path length == len(digits), add to result. O(4^n).", "code": "def letter_combinations(digits: str) -> list[str]:\n    if not digits:\n        return []\n    mapping = {'2':'abc','3':'def','4':'ghi','5':'jkl','6':'mno','7':'pqrs','8':'tuv','9':'wxyz'}\n    res = []\n    def backtrack(i, path):\n        if i == len(digits):\n            res.append(''.join(path))\n            return\n        for c in mapping[digits[i]]:\n            backtrack(i + 1, path + [c])\n    backtrack(0, [])\n    return res"},
    # ── Graphs ──
    {"problem": "Clone an undirected graph (each node has a list of neighbors).", "reasoning": "DFS with hash map to track visited/cloned nodes. For each neighbor, recursively clone if not visited, then add to current node's neighbors list. Return cloned node. O(V + E) time and space.", "code": "def clone_graph(node):\n    if not node:\n        return None\n    clones = {}\n    def dfs(n):\n        if n in clones:\n            return clones[n]\n        copy = Node(n.val)\n        clones[n] = copy\n        for nei in n.neighbors:\n            copy.neighbors.append(dfs(nei))\n        return copy\n    return dfs(node)"},
    {"problem": "Find the number of connected components in an undirected graph.", "reasoning": "DFS from each unvisited node. Each DFS traverses one connected component. Track visited set. Count how many DFS starts. O(V + E).", "code": "def count_components(n: int, edges: list[list[int]]) -> int:\n    adj = [[] for _ in range(n)]\n    for a, b in edges:\n        adj[a].append(b)\n        adj[b].append(a)\n    visited = [False] * n\n    def dfs(v):\n        visited[v] = True\n        for nei in adj[v]:\n            if not visited[nei]:\n                dfs(nei)\n    count = 0\n    for v in range(n):\n        if not visited[v]:\n            count += 1\n            dfs(v)\n    return count"},
    # ── Dynamic Programming ──
    {"problem": "Given an array of integers, find the contiguous subarray with the largest sum.", "reasoning": "Kadane's algorithm. Track current_max and global_max. For each num, current_max = max(num, current_max + num). If current_max > global_max, update. O(n) time, O(1) space.", "code": "def max_subarray(nums: list[int]) -> int:\n    cur = best = nums[0]\n    for n in nums[1:]:\n        cur = max(n, cur + n)\n        best = max(best, cur)\n    return best"},
    {"problem": "Given a 2D grid of 0/1, find the size of the largest square containing only 1s.", "reasoning": "DP where dp[i][j] = side length of largest square ending at (i,j). If grid[i][j]==1, dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]). Track max side. O(m*n) time and space, can be O(n) space.", "code": "def maximal_square(grid: list[list[str]]) -> int:\n    if not grid:\n        return 0\n    dp = [0] * (len(grid[0]) + 1)\n    best = 0\n    for i in range(len(grid)):\n        new = [0] * (len(grid[0]) + 1)\n        for j in range(len(grid[0])):\n            if grid[i][j] == '1':\n                new[j+1] = 1 + min(dp[j+1], new[j], dp[j])\n                best = max(best, new[j+1])\n        dp = new\n    return best * best"},
    {"problem": "Given a set of coins and an amount, find minimum number of coins needed to make that amount.", "reasoning": "DP with bottom-up. dp[i] = min coins to make amount i. Initialize dp[0]=0, others=inf. For each coin, for each amount from coin to target, dp[a] = min(dp[a], 1 + dp[a-coin]). Return dp[amount] or -1. O(amount * coins).", "code": "def coin_change(coins: list[int], amount: int) -> int:\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for coin in coins:\n        for a in range(coin, amount + 1):\n            dp[a] = min(dp[a], dp[a - coin] + 1)\n    return dp[amount] if dp[amount] != float('inf') else -1"},
    {"problem": "Find the length of the longest increasing subsequence.", "reasoning": "DP O(n^2): dp[i] = LIS ending at i. For each i, check all j < i. If nums[j] < nums[i], dp[i] = max(dp[i], dp[j] + 1). Return max dp. Optimization: patience sort with binary search O(n log n).", "code": "def lis_length(nums: list[int]) -> int:\n    import bisect\n    tails = []\n    for n in nums:\n        i = bisect.bisect_left(tails, n)\n        if i == len(tails):\n            tails.append(n)\n        else:\n            tails[i] = n\n    return len(tails)"},
    # ── Intervals ──
    {"problem": "Merge overlapping intervals.", "reasoning": "Sort by start time. Iterate. If current interval overlaps with last in result (curr.start <= last.end), merge by extending last.end. Otherwise append new interval. O(n log n) due to sorting.", "code": "def merge_intervals(intervals: list[list[int]]) -> list[list[int]]:\n    intervals.sort(key=lambda x: x[0])\n    merged = [intervals[0]]\n    for s, e in intervals[1:]:\n        if s <= merged[-1][1]:\n            merged[-1][1] = max(merged[-1][1], e)\n        else:\n            merged.append([s, e])\n    return merged"},
    # ── Math ──
    {"problem": "Given a signed 32-bit integer, reverse its digits.", "reasoning": "Extract digits with % 10 and build result. Check for overflow before adding each digit: if result > INT_MAX/10 or (result == INT_MAX/10 and pop > 7) then overflow. Handle negative sign separately.", "code": "def reverse_int(x: int) -> int:\n    INT_MAX = 2**31 - 1\n    sign = -1 if x < 0 else 1\n    x = abs(x)\n    res = 0\n    while x:\n        pop = x % 10\n        x //= 10\n        if res > INT_MAX // 10 or (res == INT_MAX // 10 and pop > 7):\n            return 0\n        res = res * 10 + pop\n    return sign * res"},
    {"problem": "Check if a number is a power of three.", "reasoning": "Keep dividing by 3. If n <= 0, False. While n % 3 == 0, n //= 3. Return n == 1. O(log_3 n) time.", "code": "def is_power_of_three(n: int) -> bool:\n    if n <= 0:\n        return False\n    while n % 3 == 0:\n        n //= 3\n    return n == 1"},
    # ── String ──
    {"problem": "Given a string, find the first non-repeating character and return its index. If none, return -1.", "reasoning": "Count frequencies with Counter. Then iterate through string and return first index where count == 1. O(n) time, O(1) space (26 letters).", "code": "from collections import Counter\n\ndef first_unique_char(s: str) -> int:\n    counts = Counter(s)\n    for i, c in enumerate(s):\n        if counts[c] == 1:\n            return i\n    return -1"},
    {"problem": "Implement strStr(): return index of first occurrence of needle in haystack, or -1 if not found.", "reasoning": "Edge cases: if needle empty, return 0. Slide window of len(needle) across haystack. If haystack[i:i+ln] == needle, return i. O(n*m) worst case. KMP gives O(n+m).", "code": "def str_str(haystack: str, needle: str) -> int:\n    if not needle:\n        return 0\n    ln = len(needle)\n    for i in range(len(haystack) - ln + 1):\n        if haystack[i:i+ln] == needle:\n            return i\n    return -1"},
    # ── Heap / Priority Queue ──
    {"problem": "Find the kth largest element in an array.", "reasoning": "Use a min-heap of size k. Push elements into heap. If heap size > k, pop smallest. At end, heap[0] is kth largest. O(n log k) time.", "code": "import heapq\n\ndef find_kth_largest(nums: list[int], k: int) -> int:\n    heap = []\n    for n in nums:\n        heapq.heappush(heap, n)\n        if len(heap) > k:\n            heapq.heappop(heap)\n    return heap[0]"},
    # ── Bit Manipulation ──
    {"problem": "Given an array where every element appears twice except one, find the single element.", "reasoning": "XOR all numbers. a XOR a = 0, and XOR is commutative. All paired numbers cancel out, leaving the single element. O(n) time, O(1) space.", "code": "def single_number(nums: list[int]) -> int:\n    res = 0\n    for n in nums:\n        res ^= n\n    return res"},
    {"problem": "Count the number of 1 bits in an integer (Hamming weight).", "reasoning": "Brian Kernighan's algorithm: repeatedly flip the least significant set bit: n & (n-1). Count iterations. O(number of 1 bits).", "code": "def hamming_weight(n: int) -> int:\n    count = 0\n    while n:\n        n &= n - 1\n        count += 1\n    return count"},
    # ── Concurrency ──
    {"problem": "Implement a thread-safe singleton pattern in Python.", "reasoning": "Use a class-level lock. Double-checked locking: check if instance exists (no lock), then acquire lock, check again, then create. But Python has simpler: use a module (import is thread-safe), or use 'from threading import Lock'.", "code": "from threading import Lock\n\nclass Singleton:\n    _inst = None\n    _lock = Lock()\n    def __new__(cls):\n        if cls._inst is None:\n            with cls._lock:\n                if cls._inst is None:\n                    cls._inst = super().__new__(cls)\n        return cls._inst"},
    {"problem": "Use asyncio to fetch multiple URLs concurrently.", "reasoning": "Use aiohttp with asyncio.gather. Create a ClientSession, define async fetch function. Create list of tasks with gather(), which runs them concurrently. Use semaphore to limit concurrency.", "code": "import asyncio\nimport aiohttp\n\nasync def fetch(url, session, sem):\n    async with sem:\n        async with session.get(url) as r:\n            return await r.text()\n\nasync def fetch_all(urls, concurrency=10):\n    sem = asyncio.Semaphore(concurrency)\n    async with aiohttp.ClientSession() as session:\n        tasks = [fetch(u, session, sem) for u in urls]\n        return await asyncio.gather(*tasks)"},
    # ── SQL ──
    {"problem": "Write SQL to find the second highest salary from an Employee table (id, salary).", "reasoning": "Use LIMIT/OFFSET: select distinct salary, order by desc, limit 1 offset 1. Or use subquery: select max(salary) where salary < (select max(salary) from employee). Handle null if no second highest.", "code": "SELECT MAX(salary) AS SecondHighestSalary\nFROM Employee\nWHERE salary < (SELECT MAX(salary) FROM Employee)"},
    {"problem": "Write SQL to rank employees by salary within each department.", "reasoning": "Use DENSE_RANK() window function partitioned by departmentId and ordered by salary desc. Then filter rank = 1. This gives all top earners per department, including ties.", "code": "SELECT Department, Employee, Salary\nFROM (\n  SELECT d.name AS Department, e.name AS Employee, e.salary AS Salary,\n         DENSE_RANK() OVER (PARTITION BY e.departmentId ORDER BY e.salary DESC) AS rnk\n  FROM Employee e JOIN Department d ON e.departmentId = d.id\n) ranked\nWHERE rnk = 1"},
    # ── System Design ──
    {"problem": "Design a URL shortener like TinyURL.", "reasoning": "Core: hash mapping from short code to long URL. Use base62 encoding (a-zA-Z0-9) for short codes. Store in DB (id, short_code, long_url, created_at). Handle collisions with unique constraint. Redirect: 301 from short URL to long. Cache hot URLs in Redis.", "code": "import string, random\n\nclass URLShortener:\n    def __init__(self):\n        self.store = {}  # short -> long\n        self.chars = string.ascii_letters + string.digits\n    def _gen_code(self, length=6):\n        return ''.join(random.choices(self.chars, k=length))\n    def shorten(self, long_url: str) -> str:\n        code = self._gen_code()\n        while code in self.store:\n            code = self._gen_code()\n        self.store[code] = long_url\n        return f'https://short.ly/{code}'\n    def resolve(self, code: str) -> str:\n        return self.store.get(code, None)"},
    # ── Networking ──
    {"problem": "Explain how TCP three-way handshake works and why it's needed.", "reasoning": "Client sends SYN (synchronize) with initial sequence number. Server responds with SYN-ACK (acknowledging client's seq + 1, and sending its own seq). Client sends ACK (acknowledging server's seq + 1). This establishes bidirectional communication, prevents duplicate connections from stale packets, and synchronizes sequence numbers for reliable data transfer.", "code": "# No code — conceptual explanation.\n# 1. Client -> Server: SYN (seq=x)\n# 2. Server -> Client: SYN-ACK (seq=y, ack=x+1)\n# 3. Client -> Server: ACK (seq=x+1, ack=y+1)\n# Connection established. Data transfer begins."},
    # ── Debugging ──
    {"problem": "This Python code has a bug: def append_to_list(val, lst=[]): lst.append(val); return lst. Why? How to fix?", "reasoning": "Default mutable arguments are evaluated once at function definition, not each call. So lst=[] is shared across all calls. Subsequent calls reuse the same list. Fix: use None default and create new list inside: def append_to_list(val, lst=None): if lst is None: lst = []; lst.append(val); return lst.", "code": "def append_to_list(val, lst=None):\n    if lst is None:\n        lst = []\n    lst.append(val)\n    return lst"},
    {"problem": "Debug: Why does this loop not terminate? i = 0; while i < 10: if i % 2 == 0: continue; print(i); i += 1", "reasoning": "When i is even (starting at 0), continue skips the increment. i stays 0 forever, infinite loop. Fix: move i += 1 before continue, or use for loop instead of while.", "code": "for i in range(10):\n    if i % 2 == 0:\n        continue\n    print(i)"},
    # ── Regex ──
    {"problem": "Write a regex to validate an email address.", "reasoning": "Pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$. This checks local part (alphanumerics, dots, underscores, percent, plus, hyphen), @ symbol, domain (alphanumerics, dots, hyphens), and TLD (at least 2 alpha chars).", "code": 'import re\n\ndef is_valid_email(email: str) -> bool:\n    pattern = r\'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$\'\n    return bool(re.match(pattern, email))'},
    # ── Common Sense Coding ──
    {"problem": "Write a decorator that measures function execution time.", "reasoning": "Use functools.wraps to preserve metadata. In wrapper, record time before call, call function, record time after, print difference. Return wrapper.", "code": "import time\nfrom functools import wraps\n\ndef timer(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        start = time.perf_counter()\n        result = func(*args, **kwargs)\n        elapsed = time.perf_counter() - start\n        print(f'{func.__name__} took {elapsed:.4f}s')\n        return result\n    return wrapper"},
    {"problem": "Implement a simple rate limiter using a sliding window.", "reasoning": "Track timestamps of requests per key. On each request, remove timestamps older than window. If count >= limit, reject. Otherwise add timestamp and allow. O(n) in window size; can optimize with deque or Redis.", "code": "from collections import defaultdict\nfrom time import time\n\nclass RateLimiter:\n    def __init__(self, limit=10, window=60):\n        self.limit = limit\n        self.window = window\n        self.requests = defaultdict(list)\n    def allow(self, key: str) -> bool:\n        now = time()\n        ts_list = self.requests[key]\n        while ts_list and ts_list[0] < now - self.window:\n            ts_list.pop(0)\n        if len(ts_list) >= self.limit:\n            return False\n        ts_list.append(now)\n        return True"},
]


def generate():
    path = CACHE / "synthetic_code_reasoning.pkl"
    texts = []
    for s in SAMPLES:
        t = f"<|user|>\n{s['problem']}\n<|reasoning|>\n{s['reasoning']}\n<|assistant|>\n{s['code']}\n<|end|>"
        texts.append(t)
    pickle.dump(texts, open(path, "wb"))
    print(f"Generated {len(texts)} synthetic code+reasoning samples -> {path}")


if __name__ == "__main__":
    generate()
